import React from 'react';

const Vision = () => {
  return (
    <div>
      <h1>Vision</h1>
      <p>You were not born with the ability to fly, cure disease or communicate at long distances, but you were born in a society that endows you with these capacities. These capacities are the result of information that has been generated by humans and that humans have been able to embed in tangible and digital objects.</p>
      <p>This information is all around you. It is the way in which the atoms in an airplane are arranged or the way in which your cell-phone whispers dance instructions to electromagnetic waves.</p>
      <p>Pantheon is a project celebrating the cultural information that endows our species with these fantastic capacities. To celebrate our global cultural heritage we are compiling, analyzing and visualizing datasets that can help us understand the process of global cultural development. Dive in, visualize, and enjoy.</p>
      <h2>The Ghosts of Information</h2>
      <iframe src="https://player.vimeo.com/video/89016128" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
      <h2>Mapping Global Cultural Production</h2>
      <iframe src="https://player.vimeo.com/video/89015710?color=222222&title=0&byline=0&portrait=0" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    </div>
  );
};

export default Vision;
