import {DEFAULT_LOCALE, SUPPORTED_LOCALES} from "./locales.js";
import {getExploreTranslations} from "./exploreTranslations.js";

const messages = {
  en: {
    culturalProductionIn: "Cultural Production in",
    presentDay: "Present Day",
    overlappingLives: "Overlapping Lives",
    iconCountry: "Country profile icon",
    iconPlace: "Place profile icon",
    readMoreWikipedia: "Read more on Wikipedia",
    rankIntro: "{location} ranks #{rank} by number of biographies on Pantheon, behind",
    famousBorn: "The most famous people from {location} are",
    famousDied: "The most famous people who died in {location} are",
    birthOccupations: "{location} has been the birthplace of many",
    deathOccupations: "and the death place of many",
    topCities: "The top cities in {location} by number of people born are",
    locatedIn: "{place} is located in",
    inYear: "In {year}",
    betweenYears: "Between {oldest} and {youngest}",
    birthNarrative: "{time}, present-day {location} was the birthplace of {count} globally memorable people, including",
    deathNarrative: "Additionally, {count} globally memorable people died in present-day {location}, including",
    moreDeaths: "Interestingly, more notable people died in {location} than were born there.",
    bornHeading: "People Born in Present-Day {location}",
    newBornHeading: "Newly Added People Born in Present-Day {location}",
    diedHeading: "People Deceased in Present-Day {location}",
    newDiedHeading: "Newly Added People Deceased in Present-Day {location}",
    goAllRankings: "Go to all Rankings",
    mostBorn: "Most people born in present-day {location} were",
    mostDied: "while most who died were",
    occupationsBornTitle: "Occupations of People Born in Present-Day {location}",
    occupationsDiedTitle: "Occupations of People Deceased in Present-Day {location}",
    deathPlacesTitle: "Death Places for People Born in {location}",
    birthPlacesTitle: "Birth Places for People Deceased in {location}",
    citiesDeathsTitle: "Cities by Deaths in {location}",
    citiesBirthsTitle: "Cities by Births in {location}",
    lifespanIntro: "Below is a visualization of the lifespans of the top {count} globally memorable people born in present-day {location} since 1700.",
    lifespanTitle: "Lifespans of the Top {count} People Born in {location}",
    present: "Present",
    age: "Age",
    lifespan: "Lifespan",
    yearsUnit: "years",
    clickLocation: "Click to view location",
    photoOf: "Photo of {name}",
    loadPrevious: "Load previous people",
    loadNext: "Load more people",
    notablePeople: "{count} notable people",
    countryNotFound: "Country Not Found | Pantheon",
    placeNotFound: "Place Not Found | Pantheon",
    countryMetaTitle: "{count} Famous People from {location} | Pantheon",
    countryMetaDescription: "Explore {count} historically significant people born in {location}. Discover notable leaders, artists, scientists, athletes, and more throughout history.",
    countryMetaKeywords: "{location} famous people, notable people from {location}, {location} historical figures",
    placeMetaTitle: "{count} Famous People from {location} | Pantheon",
    placeMetaDescription: "Explore {count} historically significant people born in {location}. Discover notable leaders, artists, scientists, athletes, and more from this city throughout history.",
    placeMetaKeywords: "{location} famous people, famous people from {location}, notable people born in {location}, {location} historical figures",
  },
  es: {
    culturalProductionIn: "Producción cultural en", presentDay: "Actualidad", overlappingLives: "Vidas superpuestas", iconCountry: "Icono del perfil del país", iconPlace: "Icono del perfil del lugar", readMoreWikipedia: "Leer más en Wikipedia",
    rankIntro: "{location} ocupa el puesto #{rank} por número de biografías en Pantheon, detrás de", famousBorn: "Las personas más famosas de {location} son", famousDied: "Las personas más famosas que murieron en {location} son", birthOccupations: "{location} ha sido el lugar de nacimiento de muchos", deathOccupations: "y el lugar de fallecimiento de muchos", topCities: "Las principales ciudades de {location} por número de nacimientos son", locatedIn: "{place} se encuentra en",
    inYear: "En {year}", betweenYears: "Entre {oldest} y {youngest}", birthNarrative: "{time}, el actual territorio de {location} fue el lugar de nacimiento de {count} personas memorables mundialmente, entre ellas", deathNarrative: "Además, {count} personas memorables mundialmente murieron en el actual territorio de {location}, entre ellas", moreDeaths: "Curiosamente, en {location} murieron más personas notables de las que nacieron allí.",
    bornHeading: "Personas nacidas en el actual territorio de {location}", newBornHeading: "Personas recién añadidas nacidas en el actual territorio de {location}", diedHeading: "Personas fallecidas en el actual territorio de {location}", newDiedHeading: "Personas recién añadidas fallecidas en el actual territorio de {location}", goAllRankings: "Ver todas las clasificaciones",
    mostBorn: "La mayoría de las personas nacidas en el actual territorio de {location} fueron", mostDied: "mientras que la mayoría de quienes murieron fueron", occupationsBornTitle: "Ocupaciones de las personas nacidas en el actual territorio de {location}", occupationsDiedTitle: "Ocupaciones de las personas fallecidas en el actual territorio de {location}", deathPlacesTitle: "Lugares de fallecimiento de personas nacidas en {location}", birthPlacesTitle: "Lugares de nacimiento de personas fallecidas en {location}", citiesDeathsTitle: "Ciudades por fallecimientos en {location}", citiesBirthsTitle: "Ciudades por nacimientos en {location}", lifespanIntro: "A continuación se visualizan las vidas de las {count} personas más memorables mundialmente nacidas en el actual territorio de {location} desde 1700.", lifespanTitle: "Vidas de las {count} principales personas nacidas en {location}", present: "Presente", age: "Edad", lifespan: "Esperanza de vida", yearsUnit: "años", clickLocation: "Haz clic para ver el lugar", photoOf: "Foto de {name}", loadPrevious: "Cargar personas anteriores", loadNext: "Cargar más personas", notablePeople: "{count} personas notables",
    countryNotFound: "País no encontrado | Pantheon", placeNotFound: "Lugar no encontrado | Pantheon", countryMetaTitle: "{count} personas famosas de {location} | Pantheon", countryMetaDescription: "Explora {count} personas de importancia histórica nacidas en {location}. Descubre líderes, artistas, científicos, deportistas y más.", countryMetaKeywords: "personas famosas de {location}, personas notables de {location}, figuras históricas de {location}", placeMetaTitle: "{count} personas famosas de {location} | Pantheon", placeMetaDescription: "Explora {count} personas de importancia histórica nacidas en {location}. Descubre líderes, artistas, científicos, deportistas y más de esta ciudad.", placeMetaKeywords: "personas famosas de {location}, nacidos en {location}, figuras históricas de {location}",
  },
  fr: {
    culturalProductionIn: "Production culturelle en", presentDay: "Époque actuelle", overlappingLives: "Vies qui se chevauchent", iconCountry: "Icône du profil du pays", iconPlace: "Icône du profil du lieu", readMoreWikipedia: "En savoir plus sur Wikipédia",
    rankIntro: "{location} occupe le rang #{rank} par nombre de biographies sur Pantheon, derrière", famousBorn: "Les personnes les plus célèbres de {location} sont", famousDied: "Les personnes les plus célèbres décédées à {location} sont", birthOccupations: "{location} a vu naître de nombreux", deathOccupations: "et a été le lieu de décès de nombreux", topCities: "Les principales villes de {location} par nombre de naissances sont", locatedIn: "{place} se situe en",
    inYear: "En {year}", betweenYears: "Entre {oldest} et {youngest}", birthNarrative: "{time}, le territoire actuel de {location} a vu naître {count} personnes mémorables dans le monde, dont", deathNarrative: "De plus, {count} personnes mémorables dans le monde sont décédées sur le territoire actuel de {location}, dont", moreDeaths: "Fait intéressant, davantage de personnes notables sont décédées à {location} qu’il n’en est né.",
    bornHeading: "Personnes nées dans l’actuel territoire de {location}", newBornHeading: "Personnes récemment ajoutées nées dans l’actuel territoire de {location}", diedHeading: "Personnes décédées dans l’actuel territoire de {location}", newDiedHeading: "Personnes récemment ajoutées décédées dans l’actuel territoire de {location}", goAllRankings: "Voir tous les classements",
    mostBorn: "La plupart des personnes nées dans le territoire actuel de {location} étaient", mostDied: "tandis que la plupart de celles qui y sont décédées étaient", occupationsBornTitle: "Professions des personnes nées dans le territoire actuel de {location}", occupationsDiedTitle: "Professions des personnes décédées dans le territoire actuel de {location}", deathPlacesTitle: "Lieux de décès des personnes nées à {location}", birthPlacesTitle: "Lieux de naissance des personnes décédées à {location}", citiesDeathsTitle: "Villes par nombre de décès en {location}", citiesBirthsTitle: "Villes par nombre de naissances en {location}", lifespanIntro: "Voici une visualisation de la vie des {count} personnes les plus mémorables au monde nées dans le territoire actuel de {location} depuis 1700.", lifespanTitle: "Vies des {count} principales personnes nées à {location}", present: "Présent", age: "Âge", lifespan: "Durée de vie", yearsUnit: "ans", clickLocation: "Cliquer pour voir le lieu", photoOf: "Photo de {name}", loadPrevious: "Charger les personnes précédentes", loadNext: "Charger plus de personnes", notablePeople: "{count} personnes notables",
    countryNotFound: "Pays introuvable | Pantheon", placeNotFound: "Lieu introuvable | Pantheon", countryMetaTitle: "{count} personnes célèbres de {location} | Pantheon", countryMetaDescription: "Découvrez {count} personnes d’importance historique nées en {location}, parmi lesquelles des dirigeants, artistes, scientifiques et athlètes.", countryMetaKeywords: "personnes célèbres de {location}, personnalités de {location}, figures historiques de {location}", placeMetaTitle: "{count} personnes célèbres de {location} | Pantheon", placeMetaDescription: "Découvrez {count} personnes d’importance historique nées à {location}, parmi lesquelles des dirigeants, artistes, scientifiques et athlètes de cette ville.", placeMetaKeywords: "personnes célèbres de {location}, personnes nées à {location}, figures historiques de {location}",
  },
  de: {
    culturalProductionIn: "Kulturelle Produktion in", presentDay: "Gegenwart", overlappingLives: "Sich überschneidende Leben", iconCountry: "Symbol des Länderprofils", iconPlace: "Symbol des Ortsprofils", readMoreWikipedia: "Mehr auf Wikipedia lesen",
    rankIntro: "{location} belegt nach Anzahl der Pantheon-Biografien Rang #{rank}, hinter", famousBorn: "Die berühmtesten Menschen aus {location} sind", famousDied: "Die berühmtesten Menschen, die in {location} starben, sind", birthOccupations: "{location} war Geburtsort vieler", deathOccupations: "und Sterbeort vieler", topCities: "Die wichtigsten Städte in {location} nach Geburtenzahl sind", locatedIn: "{place} liegt in",
    inYear: "Im Jahr {year}", betweenYears: "Zwischen {oldest} und {youngest}", birthNarrative: "{time} wurden im heutigen {location} {count} weltweit bekannte Menschen geboren, darunter", deathNarrative: "Außerdem starben im heutigen {location} {count} weltweit bekannte Menschen, darunter", moreDeaths: "Interessanterweise starben in {location} mehr bekannte Menschen, als dort geboren wurden.", bornHeading: "Im heutigen {location} geborene Menschen", newBornHeading: "Neu hinzugefügte, im heutigen {location} geborene Menschen", diedHeading: "Im heutigen {location} verstorbene Menschen", newDiedHeading: "Neu hinzugefügte, im heutigen {location} verstorbene Menschen", goAllRankings: "Alle Ranglisten anzeigen",
    mostBorn: "Die meisten im heutigen {location} geborenen Personen waren", mostDied: "während die meisten dort Verstorbenen waren", occupationsBornTitle: "Berufe der im heutigen {location} geborenen Menschen", occupationsDiedTitle: "Berufe der im heutigen {location} verstorbenen Menschen", deathPlacesTitle: "Sterbeorte der in {location} geborenen Menschen", birthPlacesTitle: "Geburtsorte der in {location} verstorbenen Menschen", citiesDeathsTitle: "Städte nach Todesfällen in {location}", citiesBirthsTitle: "Städte nach Geburten in {location}", lifespanIntro: "Unten sehen Sie die Lebensspannen der {count} weltweit bekanntesten Menschen, die seit 1700 im heutigen {location} geboren wurden.", lifespanTitle: "Lebensspannen der {count} wichtigsten in {location} geborenen Menschen", present: "Heute", age: "Alter", lifespan: "Lebensspanne", yearsUnit: "Jahre", clickLocation: "Klicken, um den Ort anzusehen", photoOf: "Foto von {name}", loadPrevious: "Vorherige Personen laden", loadNext: "Weitere Personen laden", notablePeople: "{count} bekannte Personen",
    countryNotFound: "Land nicht gefunden | Pantheon", placeNotFound: "Ort nicht gefunden | Pantheon", countryMetaTitle: "{count} berühmte Menschen aus {location} | Pantheon", countryMetaDescription: "Entdecken Sie {count} historisch bedeutende Menschen, die in {location} geboren wurden, darunter Führungspersönlichkeiten, Künstler, Wissenschaftler und Sportler.", countryMetaKeywords: "berühmte Menschen aus {location}, bekannte Personen aus {location}, historische Persönlichkeiten aus {location}", placeMetaTitle: "{count} berühmte Menschen aus {location} | Pantheon", placeMetaDescription: "Entdecken Sie {count} historisch bedeutende Menschen aus {location}, darunter Führungspersönlichkeiten, Künstler, Wissenschaftler und Sportler dieser Stadt.", placeMetaKeywords: "berühmte Menschen aus {location}, in {location} geboren, historische Persönlichkeiten aus {location}",
  },
  nl: {
    culturalProductionIn: "Culturele productie in", presentDay: "Heden", overlappingLives: "Overlappende levens", iconCountry: "Pictogram van het landprofiel", iconPlace: "Pictogram van het plaatsprofiel", readMoreWikipedia: "Lees meer op Wikipedia",
    rankIntro: "{location} staat op plaats #{rank} naar aantal biografieën op Pantheon, achter", famousBorn: "De beroemdste mensen uit {location} zijn", famousDied: "De beroemdste mensen die in {location} zijn overleden zijn", birthOccupations: "{location} was de geboorteplaats van veel", deathOccupations: "en de sterfplaats van veel", topCities: "De belangrijkste steden in {location} naar aantal geboorten zijn", locatedIn: "{place} ligt in",
    inYear: "In {year}", betweenYears: "Tussen {oldest} en {youngest}", birthNarrative: "{time} was het huidige {location} de geboorteplaats van {count} wereldwijd bekende mensen, waaronder", deathNarrative: "Daarnaast overleden {count} wereldwijd bekende mensen in het huidige {location}, waaronder", moreDeaths: "Opmerkelijk genoeg overleden in {location} meer bekende mensen dan er werden geboren.", bornHeading: "Mensen geboren in het huidige {location}", newBornHeading: "Nieuw toegevoegde mensen geboren in het huidige {location}", diedHeading: "Mensen overleden in het huidige {location}", newDiedHeading: "Nieuw toegevoegde mensen overleden in het huidige {location}", goAllRankings: "Bekijk alle ranglijsten",
    mostBorn: "De meeste mensen die in het huidige {location} zijn geboren waren", mostDied: "terwijl de meesten die er overleden waren", occupationsBornTitle: "Beroepen van mensen geboren in het huidige {location}", occupationsDiedTitle: "Beroepen van mensen overleden in het huidige {location}", deathPlacesTitle: "Sterfplaatsen van mensen geboren in {location}", birthPlacesTitle: "Geboorteplaatsen van mensen overleden in {location}", citiesDeathsTitle: "Steden naar sterfgevallen in {location}", citiesBirthsTitle: "Steden naar geboorten in {location}", lifespanIntro: "Hieronder staat een visualisatie van de levensduur van de {count} wereldwijd bekendste mensen die sinds 1700 in het huidige {location} zijn geboren.", lifespanTitle: "Levensduur van de {count} belangrijkste mensen geboren in {location}", present: "Heden", age: "Leeftijd", lifespan: "Levensduur", yearsUnit: "jaar", clickLocation: "Klik om de plaats te bekijken", photoOf: "Foto van {name}", loadPrevious: "Vorige personen laden", loadNext: "Meer personen laden", notablePeople: "{count} bekende personen",
    countryNotFound: "Land niet gevonden | Pantheon", placeNotFound: "Plaats niet gevonden | Pantheon", countryMetaTitle: "{count} beroemde mensen uit {location} | Pantheon", countryMetaDescription: "Ontdek {count} historisch belangrijke mensen die in {location} zijn geboren, waaronder leiders, kunstenaars, wetenschappers en sporters.", countryMetaKeywords: "beroemde mensen uit {location}, bekende personen uit {location}, historische figuren uit {location}", placeMetaTitle: "{count} beroemde mensen uit {location} | Pantheon", placeMetaDescription: "Ontdek {count} historisch belangrijke mensen uit {location}, waaronder leiders, kunstenaars, wetenschappers en sporters uit deze stad.", placeMetaKeywords: "beroemde mensen uit {location}, geboren in {location}, historische figuren uit {location}",
  },
  it: {
    culturalProductionIn: "Produzione culturale in", presentDay: "Oggi", overlappingLives: "Vite sovrapposte", iconCountry: "Icona del profilo del paese", iconPlace: "Icona del profilo del luogo", readMoreWikipedia: "Leggi di più su Wikipedia",
    rankIntro: "{location} è al posto #{rank} per numero di biografie su Pantheon, dietro", famousBorn: "Le persone più famose di {location} sono", famousDied: "Le persone più famose morte a {location} sono", birthOccupations: "{location} ha dato i natali a molti", deathOccupations: "ed è stato il luogo di morte di molti", topCities: "Le principali città di {location} per numero di nascite sono", locatedIn: "{place} si trova in",
    inYear: "Nel {year}", betweenYears: "Tra il {oldest} e il {youngest}", birthNarrative: "{time}, l’attuale territorio di {location} ha dato i natali a {count} persone memorabili nel mondo, tra cui", deathNarrative: "Inoltre, {count} persone memorabili nel mondo sono morte nell’attuale territorio di {location}, tra cui", moreDeaths: "È interessante notare che a {location} sono morte più persone note di quante ne siano nate.", bornHeading: "Persone nate nell’attuale territorio di {location}", newBornHeading: "Persone appena aggiunte nate nell’attuale territorio di {location}", diedHeading: "Persone decedute nell’attuale territorio di {location}", newDiedHeading: "Persone appena aggiunte decedute nell’attuale territorio di {location}", goAllRankings: "Vai a tutte le classifiche",
    mostBorn: "La maggior parte delle persone nate nell’attuale territorio di {location} erano", mostDied: "mentre la maggior parte di quelle morte erano", occupationsBornTitle: "Professioni delle persone nate nell’attuale territorio di {location}", occupationsDiedTitle: "Professioni delle persone decedute nell’attuale territorio di {location}", deathPlacesTitle: "Luoghi di morte delle persone nate a {location}", birthPlacesTitle: "Luoghi di nascita delle persone decedute a {location}", citiesDeathsTitle: "Città per decessi in {location}", citiesBirthsTitle: "Città per nascite in {location}", lifespanIntro: "Di seguito è visualizzata la durata della vita delle {count} persone più memorabili nel mondo nate nell’attuale territorio di {location} dal 1700.", lifespanTitle: "Vite delle {count} principali persone nate a {location}", present: "Presente", age: "Età", lifespan: "Durata della vita", yearsUnit: "anni", clickLocation: "Fai clic per vedere il luogo", photoOf: "Foto di {name}", loadPrevious: "Carica persone precedenti", loadNext: "Carica altre persone", notablePeople: "{count} persone notevoli",
    countryNotFound: "Paese non trovato | Pantheon", placeNotFound: "Luogo non trovato | Pantheon", countryMetaTitle: "{count} persone famose di {location} | Pantheon", countryMetaDescription: "Scopri {count} persone storicamente importanti nate in {location}, tra cui leader, artisti, scienziati e atleti.", countryMetaKeywords: "persone famose di {location}, persone notevoli di {location}, figure storiche di {location}", placeMetaTitle: "{count} persone famose di {location} | Pantheon", placeMetaDescription: "Scopri {count} persone storicamente importanti nate a {location}, tra cui leader, artisti, scienziati e atleti di questa città.", placeMetaKeywords: "persone famose di {location}, nati a {location}, figure storiche di {location}",
  },
  pt: {
    culturalProductionIn: "Produção cultural em", presentDay: "Atualidade", overlappingLives: "Vidas sobrepostas", iconCountry: "Ícone do perfil do país", iconPlace: "Ícone do perfil do lugar", readMoreWikipedia: "Leia mais na Wikipédia",
    rankIntro: "{location} ocupa a posição #{rank} por número de biografias no Pantheon, atrás de", famousBorn: "As pessoas mais famosas de {location} são", famousDied: "As pessoas mais famosas que morreram em {location} são", birthOccupations: "{location} foi o local de nascimento de muitos", deathOccupations: "e o local de morte de muitos", topCities: "As principais cidades de {location} por número de nascimentos são", locatedIn: "{place} fica em",
    inYear: "Em {year}", betweenYears: "Entre {oldest} e {youngest}", birthNarrative: "{time}, o atual território de {location} foi o local de nascimento de {count} pessoas mundialmente memoráveis, incluindo", deathNarrative: "Além disso, {count} pessoas mundialmente memoráveis morreram no atual território de {location}, incluindo", moreDeaths: "Curiosamente, mais pessoas notáveis morreram em {location} do que nasceram lá.", bornHeading: "Pessoas nascidas no atual território de {location}", newBornHeading: "Pessoas recém-adicionadas nascidas no atual território de {location}", diedHeading: "Pessoas falecidas no atual território de {location}", newDiedHeading: "Pessoas recém-adicionadas falecidas no atual território de {location}", goAllRankings: "Ver todas as classificações",
    mostBorn: "A maioria das pessoas nascidas no atual território de {location} eram", mostDied: "enquanto a maioria das que morreram eram", occupationsBornTitle: "Ocupações das pessoas nascidas no atual território de {location}", occupationsDiedTitle: "Ocupações das pessoas falecidas no atual território de {location}", deathPlacesTitle: "Locais de morte de pessoas nascidas em {location}", birthPlacesTitle: "Locais de nascimento de pessoas falecidas em {location}", citiesDeathsTitle: "Cidades por mortes em {location}", citiesBirthsTitle: "Cidades por nascimentos em {location}", lifespanIntro: "Abaixo está uma visualização da vida das {count} pessoas mais memoráveis do mundo nascidas no atual território de {location} desde 1700.", lifespanTitle: "Vida das {count} principais pessoas nascidas em {location}", present: "Presente", age: "Idade", lifespan: "Duração da vida", yearsUnit: "anos", clickLocation: "Clique para ver o local", photoOf: "Foto de {name}", loadPrevious: "Carregar pessoas anteriores", loadNext: "Carregar mais pessoas", notablePeople: "{count} pessoas notáveis",
    countryNotFound: "País não encontrado | Pantheon", placeNotFound: "Lugar não encontrado | Pantheon", countryMetaTitle: "{count} pessoas famosas de {location} | Pantheon", countryMetaDescription: "Explore {count} pessoas historicamente importantes nascidas em {location}, incluindo líderes, artistas, cientistas e atletas.", countryMetaKeywords: "pessoas famosas de {location}, pessoas notáveis de {location}, figuras históricas de {location}", placeMetaTitle: "{count} pessoas famosas de {location} | Pantheon", placeMetaDescription: "Explore {count} pessoas historicamente importantes nascidas em {location}, incluindo líderes, artistas, cientistas e atletas desta cidade.", placeMetaKeywords: "pessoas famosas de {location}, nascidos em {location}, figuras históricas de {location}",
  },
  pl: {
    culturalProductionIn: "Dorobek kulturowy w", presentDay: "Współcześnie", overlappingLives: "Nakładające się życia", iconCountry: "Ikona profilu kraju", iconPlace: "Ikona profilu miejsca", readMoreWikipedia: "Czytaj więcej w Wikipedii",
    rankIntro: "{location} zajmuje #{rank} miejsce pod względem liczby biografii w Pantheon, za", famousBorn: "Najsłynniejsze osoby z {location} to", famousDied: "Najsłynniejsze osoby zmarłe w {location} to", birthOccupations: "{location} jest miejscem urodzenia wielu", deathOccupations: "i miejscem śmierci wielu", topCities: "Najważniejsze miasta w {location} według liczby urodzeń to", locatedIn: "{place} znajduje się w",
    inYear: "W roku {year}", betweenYears: "Między {oldest} a {youngest}", birthNarrative: "{time} na obszarze dzisiejszego {location} urodziło się {count} osób znanych na całym świecie, w tym", deathNarrative: "Ponadto na obszarze dzisiejszego {location} zmarło {count} osób znanych na całym świecie, w tym", moreDeaths: "Co ciekawe, w {location} zmarło więcej znanych osób, niż się tam urodziło.", bornHeading: "Osoby urodzone na obszarze dzisiejszego {location}", newBornHeading: "Nowo dodane osoby urodzone na obszarze dzisiejszego {location}", diedHeading: "Osoby zmarłe na obszarze dzisiejszego {location}", newDiedHeading: "Nowo dodane osoby zmarłe na obszarze dzisiejszego {location}", goAllRankings: "Zobacz wszystkie rankingi",
    mostBorn: "Większość osób urodzonych na obszarze dzisiejszego {location} to", mostDied: "natomiast większość osób, które tam zmarły, to", occupationsBornTitle: "Zawody osób urodzonych na obszarze dzisiejszego {location}", occupationsDiedTitle: "Zawody osób zmarłych na obszarze dzisiejszego {location}", deathPlacesTitle: "Miejsca śmierci osób urodzonych w {location}", birthPlacesTitle: "Miejsca urodzenia osób zmarłych w {location}", citiesDeathsTitle: "Miasta według liczby zgonów w {location}", citiesBirthsTitle: "Miasta według liczby urodzeń w {location}", lifespanIntro: "Poniżej przedstawiono długość życia {count} najbardziej znanych na świecie osób urodzonych od 1700 roku na obszarze dzisiejszego {location}.", lifespanTitle: "Życie {count} najwyżej sklasyfikowanych osób urodzonych w {location}", present: "Obecnie", age: "Wiek", lifespan: "Długość życia", yearsUnit: "lat", clickLocation: "Kliknij, aby zobaczyć miejsce", photoOf: "Zdjęcie: {name}", loadPrevious: "Wczytaj poprzednie osoby", loadNext: "Wczytaj więcej osób", notablePeople: "{count} znanych osób",
    countryNotFound: "Nie znaleziono kraju | Pantheon", placeNotFound: "Nie znaleziono miejsca | Pantheon", countryMetaTitle: "{count} sławnych osób z {location} | Pantheon", countryMetaDescription: "Poznaj {count} ważnych historycznie osób urodzonych w {location}, w tym przywódców, artystów, naukowców i sportowców.", countryMetaKeywords: "sławne osoby z {location}, znane osoby z {location}, postacie historyczne z {location}", placeMetaTitle: "{count} sławnych osób z {location} | Pantheon", placeMetaDescription: "Poznaj {count} ważnych historycznie osób urodzonych w {location}, w tym przywódców, artystów, naukowców i sportowców z tego miasta.", placeMetaKeywords: "sławne osoby z {location}, urodzeni w {location}, postacie historyczne z {location}",
  },
  hu: {
    culturalProductionIn: "Kulturális alkotótevékenység itt:", presentDay: "Napjainkban", overlappingLives: "Átfedő életek", iconCountry: "Az országprofil ikonja", iconPlace: "A helyprofil ikonja", readMoreWikipedia: "További információ a Wikipédián",
    rankIntro: "{location} a(z) #{rank}. helyen áll a Pantheon életrajzainak száma alapján, megelőzi", famousBorn: "{location} leghíresebb szülöttei", famousDied: "A leghíresebb, {location} területén elhunyt emberek", birthOccupations: "{location} sok ember születési helye volt, köztük", deathOccupations: "és sok ember halálozási helye, köztük", topCities: "{location} legfontosabb városai a születések száma alapján", locatedIn: "{place} itt található:",
    inYear: "{year}-ban/-ben", betweenYears: "{oldest} és {youngest} között", birthNarrative: "{time} a mai {location} területén {count} világszerte emlékezetes ember született, köztük", deathNarrative: "Emellett a mai {location} területén {count} világszerte emlékezetes ember hunyt el, köztük", moreDeaths: "Érdekes módon {location} területén több ismert ember hunyt el, mint ahány ott született.", bornHeading: "A mai {location} területén született emberek", newBornHeading: "Újonnan hozzáadott, a mai {location} területén született emberek", diedHeading: "A mai {location} területén elhunyt emberek", newDiedHeading: "Újonnan hozzáadott, a mai {location} területén elhunyt emberek", goAllRankings: "Összes rangsor megtekintése",
    mostBorn: "A mai {location} területén születettek többsége", mostDied: "míg az ott elhunytak többsége", occupationsBornTitle: "A mai {location} területén születettek foglalkozásai", occupationsDiedTitle: "A mai {location} területén elhunytak foglalkozásai", deathPlacesTitle: "A {location} területén születettek halálozási helyei", birthPlacesTitle: "A {location} területén elhunytak születési helyei", citiesDeathsTitle: "Városok halálozások szerint itt: {location}", citiesBirthsTitle: "Városok születések szerint itt: {location}", lifespanIntro: "Az alábbi ábra a mai {location} területén 1700 óta született {count} világszerte legismertebb ember életét mutatja.", lifespanTitle: "A {location} területén született {count} legfontosabb ember élete", present: "Napjainkig", age: "Életkor", lifespan: "Élettartam", yearsUnit: "év", clickLocation: "Kattintson a hely megtekintéséhez", photoOf: "{name} fényképe", loadPrevious: "Korábbi emberek betöltése", loadNext: "További emberek betöltése", notablePeople: "{count} nevezetes ember",
    countryNotFound: "Az ország nem található | Pantheon", placeNotFound: "A hely nem található | Pantheon", countryMetaTitle: "{count} híres ember innen: {location} | Pantheon", countryMetaDescription: "Fedezzen fel {count}, {location} területén született történelmileg jelentős embert, köztük vezetőket, művészeket, tudósokat és sportolókat.", countryMetaKeywords: "{location} híres emberei, {location} nevezetes emberei, {location} történelmi alakjai", placeMetaTitle: "{count} híres ember innen: {location} | Pantheon", placeMetaDescription: "Fedezzen fel {count}, {location} területén született történelmileg jelentős embert, köztük a város vezetőit, művészeit, tudósait és sportolóit.", placeMetaKeywords: "{location} híres emberei, {location} szülöttei, {location} történelmi alakjai",
  },
  ru: {
    culturalProductionIn: "Культурное наследие в", presentDay: "Современность", overlappingLives: "Пересекающиеся жизни", iconCountry: "Значок профиля страны", iconPlace: "Значок профиля места", readMoreWikipedia: "Подробнее в Википедии",
    rankIntro: "{location} занимает место #{rank} по числу биографий в Pantheon, после", famousBorn: "Самые известные уроженцы {location}", famousDied: "Самые известные люди, умершие в {location}", birthOccupations: "{location} — место рождения многих", deathOccupations: "и место смерти многих", topCities: "Главные города {location} по числу рождений", locatedIn: "{place} находится в",
    inYear: "В {year} году", betweenYears: "Между {oldest} и {youngest} годами", birthNarrative: "{time} на территории современного {location} родилось {count} всемирно известных людей, в том числе", deathNarrative: "Кроме того, на территории современного {location} умерло {count} всемирно известных людей, в том числе", moreDeaths: "Примечательно, что в {location} умерло больше известных людей, чем родилось.", bornHeading: "Люди, родившиеся на территории современного {location}", newBornHeading: "Недавно добавленные люди, родившиеся на территории современного {location}", diedHeading: "Люди, умершие на территории современного {location}", newDiedHeading: "Недавно добавленные люди, умершие на территории современного {location}", goAllRankings: "Все рейтинги",
    mostBorn: "Большинство людей, родившихся на территории современного {location}, были", mostDied: "а большинство умерших там были", occupationsBornTitle: "Профессии людей, родившихся на территории современного {location}", occupationsDiedTitle: "Профессии людей, умерших на территории современного {location}", deathPlacesTitle: "Места смерти людей, родившихся в {location}", birthPlacesTitle: "Места рождения людей, умерших в {location}", citiesDeathsTitle: "Города по числу смертей в {location}", citiesBirthsTitle: "Города по числу рождений в {location}", lifespanIntro: "Ниже показана продолжительность жизни {count} самых известных в мире людей, родившихся на территории современного {location} с 1700 года.", lifespanTitle: "Жизнь {count} самых известных людей, родившихся в {location}", present: "Настоящее время", age: "Возраст", lifespan: "Продолжительность жизни", yearsUnit: "лет", clickLocation: "Нажмите, чтобы открыть место", photoOf: "Фото: {name}", loadPrevious: "Загрузить предыдущих людей", loadNext: "Загрузить ещё людей", notablePeople: "{count} известных людей",
    countryNotFound: "Страна не найдена | Pantheon", placeNotFound: "Место не найдено | Pantheon", countryMetaTitle: "{count} известных людей из {location} | Pantheon", countryMetaDescription: "Узнайте о {count} исторически значимых людях, родившихся в {location}: лидерах, художниках, учёных, спортсменах и других.", countryMetaKeywords: "известные люди из {location}, выдающиеся люди из {location}, исторические личности {location}", placeMetaTitle: "{count} известных людей из {location} | Pantheon", placeMetaDescription: "Узнайте о {count} исторически значимых людях, родившихся в {location}: лидерах, художниках, учёных и спортсменах этого города.", placeMetaKeywords: "известные люди из {location}, родившиеся в {location}, исторические личности {location}",
  },
  zh: {
    culturalProductionIn: "文化产出地", presentDay: "现今", overlappingLives: "人生交汇", iconCountry: "国家资料图标", iconPlace: "地点资料图标", readMoreWikipedia: "在维基百科阅读更多",
    rankIntro: "按 Pantheon 收录的传记数量，{location}排名第 {rank}，排在其前的有", famousBorn: "{location}最著名的人物包括", famousDied: "在{location}去世的最著名人物包括", birthOccupations: "{location}是许多以下职业人士的出生地", deathOccupations: "也是许多以下职业人士的去世地", topCities: "{location}按出生人数排名最高的城市包括", locatedIn: "{place}位于",
    inYear: "{year}年", betweenYears: "{oldest}年至{youngest}年间", birthNarrative: "{time}，现今{location}境内诞生了 {count} 位享誉全球的人物，包括", deathNarrative: "此外，现今{location}境内共有 {count} 位享誉全球的人物去世，包括", moreDeaths: "有趣的是，在{location}去世的知名人物多于出生于此的人物。", bornHeading: "出生于现今{location}境内的人物", newBornHeading: "新收录的出生于现今{location}境内的人物", diedHeading: "去世于现今{location}境内的人物", newDiedHeading: "新收录的去世于现今{location}境内的人物", goAllRankings: "查看全部排名",
    mostBorn: "出生于现今{location}境内的人物主要从事", mostDied: "而在此去世的人物主要从事", occupationsBornTitle: "出生于现今{location}境内人物的职业", occupationsDiedTitle: "去世于现今{location}境内人物的职业", deathPlacesTitle: "出生于{location}的人物去世地", birthPlacesTitle: "在{location}去世的人物出生地", citiesDeathsTitle: "{location}各城市去世人数", citiesBirthsTitle: "{location}各城市出生人数", lifespanIntro: "下图展示了自1700年以来出生于现今{location}境内、全球知名度最高的 {count} 位人物的生平跨度。", lifespanTitle: "出生于{location}的前 {count} 位人物的生平跨度", present: "至今", age: "年龄", lifespan: "寿命", yearsUnit: "年", clickLocation: "点击查看地点", photoOf: "{name}的照片", loadPrevious: "加载前一组人物", loadNext: "加载更多人物", notablePeople: "{count} 位知名人物",
    countryNotFound: "未找到国家 | Pantheon", placeNotFound: "未找到地点 | Pantheon", countryMetaTitle: "来自{location}的 {count} 位名人 | Pantheon", countryMetaDescription: "探索出生于{location}的 {count} 位历史重要人物，包括领袖、艺术家、科学家、运动员等。", countryMetaKeywords: "{location}名人, 来自{location}的知名人物, {location}历史人物", placeMetaTitle: "来自{location}的 {count} 位名人 | Pantheon", placeMetaDescription: "探索出生于{location}的 {count} 位历史重要人物，包括这座城市的领袖、艺术家、科学家和运动员。", placeMetaKeywords: "{location}名人, 出生于{location}的人物, {location}历史人物",
  },
  ja: {
    culturalProductionIn: "文化的成果の地", presentDay: "現代", overlappingLives: "重なり合う人生", iconCountry: "国プロフィールのアイコン", iconPlace: "場所プロフィールのアイコン", readMoreWikipedia: "ウィキペディアで続きを読む",
    rankIntro: "Pantheonの伝記数で{location}は第{rank}位です。上位には", famousBorn: "{location}出身の最も有名な人物は", famousDied: "{location}で亡くなった最も有名な人物は", birthOccupations: "{location}では多くの次の職業の人物が生まれました", deathOccupations: "また、多くの次の職業の人物が亡くなりました", topCities: "{location}で出生者数が多い主な都市は", locatedIn: "{place}の所在地は",
    inYear: "{year}年", betweenYears: "{oldest}年から{youngest}年の間", birthNarrative: "{time}、現在の{location}では世界的に記憶される人物が{count}人生まれました。代表例は", deathNarrative: "さらに、現在の{location}では世界的に記憶される人物が{count}人亡くなりました。代表例は", moreDeaths: "興味深いことに、{location}では、そこで生まれた著名人よりも多くの著名人が亡くなっています。", bornHeading: "現在の{location}で生まれた人物", newBornHeading: "新たに追加された現在の{location}生まれの人物", diedHeading: "現在の{location}で亡くなった人物", newDiedHeading: "新たに追加された現在の{location}で亡くなった人物", goAllRankings: "すべてのランキングを見る",
    mostBorn: "現在の{location}で生まれた人物に多い職業は", mostDied: "一方、そこで亡くなった人物に多い職業は", occupationsBornTitle: "現在の{location}で生まれた人物の職業", occupationsDiedTitle: "現在の{location}で亡くなった人物の職業", deathPlacesTitle: "{location}で生まれた人物の死没地", birthPlacesTitle: "{location}で亡くなった人物の出生地", citiesDeathsTitle: "{location}の都市別死没者数", citiesBirthsTitle: "{location}の都市別出生者数", lifespanIntro: "下図は、1700年以降に現在の{location}で生まれた世界的に著名な上位{count}人の生涯を示しています。", lifespanTitle: "{location}で生まれた上位{count}人の生涯", present: "現在", age: "年齢", lifespan: "寿命", yearsUnit: "年", clickLocation: "クリックして場所を表示", photoOf: "{name}の写真", loadPrevious: "前の人物を読み込む", loadNext: "さらに人物を読み込む", notablePeople: "著名人物{count}人",
    countryNotFound: "国が見つかりません | Pantheon", placeNotFound: "場所が見つかりません | Pantheon", countryMetaTitle: "{location}出身の著名人物{count}人 | Pantheon", countryMetaDescription: "{location}で生まれた歴史的に重要な人物{count}人を紹介します。指導者、芸術家、科学者、スポーツ選手などを発見できます。", countryMetaKeywords: "{location}の有名人, {location}出身の著名人, {location}の歴史的人物", placeMetaTitle: "{location}出身の著名人物{count}人 | Pantheon", placeMetaDescription: "{location}で生まれた歴史的に重要な人物{count}人を紹介します。この都市の指導者、芸術家、科学者、スポーツ選手などを発見できます。", placeMetaKeywords: "{location}の有名人, {location}生まれ, {location}の歴史的人物",
  },
  ar: {
    culturalProductionIn: "الإنتاج الثقافي في", presentDay: "العصر الحاضر", overlappingLives: "حيوات متداخلة", iconCountry: "أيقونة ملف الدولة", iconPlace: "أيقونة ملف المكان", readMoreWikipedia: "اقرأ المزيد على ويكيبيديا",
    rankIntro: "تحتل {location} المرتبة {rank} حسب عدد السير في Pantheon، بعد", famousBorn: "أشهر الأشخاص من {location} هم", famousDied: "أشهر الأشخاص الذين توفوا في {location} هم", birthOccupations: "كانت {location} مسقط رأس العديد من", deathOccupations: "ومكان وفاة العديد من", topCities: "أبرز مدن {location} حسب عدد المواليد هي", locatedIn: "تقع {place} في",
    inYear: "في سنة {year}", betweenYears: "بين {oldest} و{youngest}", birthNarrative: "{time}، وُلد في أرض {location} الحالية {count} من الأشخاص البارزين عالميًا، منهم", deathNarrative: "كما توفي في أرض {location} الحالية {count} من الأشخاص البارزين عالميًا، منهم", moreDeaths: "ومن المثير للاهتمام أن عدد المشاهير الذين توفوا في {location} أكبر من عدد الذين وُلدوا فيها.", bornHeading: "أشخاص وُلدوا في أرض {location} الحالية", newBornHeading: "أشخاص مضافون حديثًا وُلدوا في أرض {location} الحالية", diedHeading: "أشخاص توفوا في أرض {location} الحالية", newDiedHeading: "أشخاص مضافون حديثًا توفوا في أرض {location} الحالية", goAllRankings: "عرض كل التصنيفات",
    mostBorn: "كان معظم المولودين في أرض {location} الحالية من", mostDied: "بينما كان معظم المتوفين فيها من", occupationsBornTitle: "مهن الأشخاص المولودين في أرض {location} الحالية", occupationsDiedTitle: "مهن الأشخاص المتوفين في أرض {location} الحالية", deathPlacesTitle: "أماكن وفاة المولودين في {location}", birthPlacesTitle: "أماكن ميلاد المتوفين في {location}", citiesDeathsTitle: "المدن حسب الوفيات في {location}", citiesBirthsTitle: "المدن حسب المواليد في {location}", lifespanIntro: "فيما يلي عرض لأعمار أبرز {count} شخص عالميًا وُلدوا في أرض {location} الحالية منذ 1700.", lifespanTitle: "أعمار أبرز {count} شخص وُلدوا في {location}", present: "حتى اليوم", age: "العمر", lifespan: "مدة الحياة", yearsUnit: "سنة", clickLocation: "انقر لعرض المكان", photoOf: "صورة {name}", loadPrevious: "تحميل الأشخاص السابقين", loadNext: "تحميل المزيد من الأشخاص", notablePeople: "{count} من الأشخاص البارزين",
    countryNotFound: "لم يتم العثور على الدولة | Pantheon", placeNotFound: "لم يتم العثور على المكان | Pantheon", countryMetaTitle: "{count} من مشاهير {location} | Pantheon", countryMetaDescription: "استكشف {count} من الشخصيات ذات الأهمية التاريخية المولودة في {location}، من القادة والفنانين والعلماء والرياضيين وغيرهم.", countryMetaKeywords: "مشاهير {location}, شخصيات بارزة من {location}, شخصيات {location} التاريخية", placeMetaTitle: "{count} من مشاهير {location} | Pantheon", placeMetaDescription: "استكشف {count} من الشخصيات ذات الأهمية التاريخية المولودة في {location}، من قادة هذه المدينة وفنانيها وعلمائها ورياضييها.", placeMetaKeywords: "مشاهير {location}, مواليد {location}, شخصيات {location} التاريخية",
  },
};

function interpolate(template, params = {}) {
  return template.replace(/\{(\w+)\}/g, (match, key) =>
    params[key] === undefined || params[key] === null ? match : `${params[key]}`,
  );
}

export function getLocationTranslations(locale = DEFAULT_LOCALE) {
  const normalized = SUPPORTED_LOCALES.includes(locale)
    ? locale
    : DEFAULT_LOCALE;
  const local = messages[normalized] || messages[DEFAULT_LOCALE];
  const explore = getExploreTranslations(normalized);

  return (key, params) => {
    const template = local[key] ?? messages[DEFAULT_LOCALE][key];
    return template ? interpolate(template, params) : explore(key, params);
  };
}

export function getLocationMessageKeys() {
  return Object.keys(messages.en);
}

export function getLocationLocaleMessages(locale) {
  return messages[locale] || null;
}
