// UI translations for different languages
export const translations = {
  en: {
    stillAlive: "today",
    intro: {
      rankingSentence: ({
        name,
        gender,
        l,
        l_prev,
        occupationRank,
        occupationRankPrev,
        occupation,
        occupationSlug,
        bplaceCountryRank,
        bplaceCountryRankPrev,
        country,
        countrySlug,
        bplaceCountryOccupationRank,
        demonym,
        formatOrdinal,
      }) => {
        const possessive = gender === "M" ? "His" : gender === "F" ? "Her" : "Their";

        let sentence = `${possessive} biography is available in ${l} different languages on Wikipedia`;
        if (l_prev && l !== l_prev) {
          sentence += ` (${l > l_prev ? "up" : "down"} from ${l_prev} in 2024)`;
        }
        sentence += ". ";

        sentence += `${name} is the ${occupationRank === 1 ? "" : formatOrdinal(occupationRank)} most popular <a href="/profile/occupation/${occupationSlug}">${occupation.toLowerCase()}</a>`;
        if (occupationRankPrev && occupationRankPrev !== occupationRank) {
          sentence += ` (${occupationRank < occupationRankPrev ? "up" : "down"} from ${formatOrdinal(occupationRankPrev)} in 2024)`;
        }

        if (country) {
          sentence += `, the ${bplaceCountryRank !== 1 ? formatOrdinal(bplaceCountryRank) : ""} most popular biography from <a href="/profile/place/${countrySlug}">${country}</a>`;
          if (bplaceCountryRankPrev && bplaceCountryRankPrev !== bplaceCountryRank) {
            sentence += ` (${bplaceCountryRank < bplaceCountryRankPrev ? "up" : "down"} from ${formatOrdinal(bplaceCountryRankPrev)} in 2019)`;
          }

          if (bplaceCountryOccupationRank) {
            sentence += ` and the ${bplaceCountryOccupationRank !== 1 ? formatOrdinal(bplaceCountryOccupationRank) : ""} most popular <a href="/profile/occupation/${occupationSlug}/country/${countrySlug}">${demonym} ${occupation}</a>`;
          }
        }

        sentence += ".";
        return sentence;
      },
    },
    nav: {
      visualizations: "Visualizations",
      rankings: "Rankings",
      profiles: "Profiles",
      people: "People",
      places: "Places",
      countries: "Countries",
      occupations: "Occupations",
      occupationCountry: "Occupation / Country",
      eras: "Eras",
      deaths: "Deaths",
      about: "About",
      data: "Data",
      permissions: "Permissions",
      download: "Download",
      api: "API",
      games: "Games",
      yearbook: "Yearbook",
      birthle: "Birthle",
      trivia: "Trivia",
      news: "News",
      search: "Search",
      home: "Home",
      giveFeedback: "Give Feedback",
      usageCitation: "Usage Citation",
      newBadge: "new!",
    },
    readMoreWikipedia: "Read more on Wikipedia",
    learnMoreRankless: "Learn more about {name}'s academic impact at Rankless",
    home: {
      tagline: "Explore human collective memory!",
      subtitle:
        "Pantheon helps you discover the geography and dynamics of our planet's history.",
      explore: "Explore",
      people: "People",
      places: "Places",
      occupations: "Occupations",
      and: "and",
      eras: "Eras",
      trendingProfiles: "Trending Profiles Today",
      topProfilesBy: "Top profiles by pageviews for the",
      wikipediaEdition: "wikipedia edition",
      about:
        "is an observatory of collective memory focused on biographies with a presence in at least",
      languages: "languages",
      aboutContinued:
        "in Wikipedia. We have data on more than 85,000 biographies, organized by countries, cities, occupations, and eras. Explore this data to learn about the characters that shape human culture.",
      aboutDeveloped:
        "began as a project at the Collective Learning group at MIT. Today it is developed by",
      datawheel: "Datawheel",
      aboutDatawheel:
        ", a company specialized in the creation of data distribution and visualization solutions.",
      recentPassings: "Recent Passings",
      notableDeaths: "Notable Deaths of 2025",
      notableDeathsText:
        "Want to see the complete list of notable figures we've lost in 2025? Visit our",
      notableDeathsLink: "Notable Deaths of 2025",
      notableDeathsContinued:
        "page for a comprehensive collection of biographies featuring influential personalities, including celebrities, artists, leaders, and cultural icons who have passed away this year.",
      trendingSingers: "Trending Singers Today",
      trendingActors: "Trending Actors Today",
      searchPlaceholder: "Search people, places, & occupations",
    },
    news: {
      pageTitle: "Who is Trending Today?",
      pageSubtitle: "Daily summaries of historical figures (generated by AI)",
      trendingIn: "Trending in",
      selectDate: "Select a different date",
      references: "References:",
      noData: "No trending data available for this date.",
      unknown: "Unknown",
    },
    trending: {
      isTrendingToday: "{name} is trending today!",
      whyTrending: "Why {name} is Trending:",
      references: "References:",
      viewMoreTrending: "View more trending people",
    },
  },
  es: {
    stillAlive: "presente",
    learnMoreRankless: "Más información sobre el impacto académico de {name} en Rankless",
    intro: {
      rankingSentence: ({
        name,
        gender,
        l,
        l_prev,
        occupationRank,
        occupationRankPrev,
        occupation,
        occupationSlug,
        bplaceCountryRank,
        bplaceCountryRankPrev,
        country,
        countrySlug,
        bplaceCountryOccupationRank,
        demonym,
        formatOrdinal,
      }) => {
        let sentence = `Su biografía está disponible en ${l} idiomas diferentes en Wikipedia`;
        if (l_prev && l !== l_prev) {
          sentence += ` (${l > l_prev ? "aumentó" : "disminuyó"} de ${l_prev} en 2024)`;
        }
        sentence += ". ";

        const article = gender === "F" ? "la" : "el";
        sentence += `${name} es ${article} ${occupationRank === 1 ? "" : formatOrdinal(occupationRank)} <a href="/profile/occupation/${occupationSlug}">${occupation.toLowerCase()}</a> más popular`;
        if (occupationRankPrev && occupationRankPrev !== occupationRank) {
          sentence += ` (${occupationRank < occupationRankPrev ? "subió" : "bajó"} del ${formatOrdinal(occupationRankPrev)} en 2024)`;
        }

        if (country) {
          sentence += `, ${article} ${bplaceCountryRank !== 1 ? formatOrdinal(bplaceCountryRank) : ""} biografía más popular de <a href="/profile/place/${countrySlug}">${country}</a>`;
          if (bplaceCountryRankPrev && bplaceCountryRankPrev !== bplaceCountryRank) {
            sentence += ` (${bplaceCountryRank < bplaceCountryRankPrev ? "subió" : "bajó"} del ${formatOrdinal(bplaceCountryRankPrev)} en 2019)`;
          }

          if (bplaceCountryOccupationRank) {
            sentence += ` y ${article} ${bplaceCountryOccupationRank !== 1 ? formatOrdinal(bplaceCountryOccupationRank) : ""} <a href="/profile/occupation/${occupationSlug}/country/${countrySlug}">${demonym} ${occupation}</a> más popular`;
          }
        }

        sentence += ".";
        return sentence;
      },
    },
    nav: {
      visualizations: "Visualizaciones",
      rankings: "Clasificaciones",
      profiles: "Perfiles",
      people: "Personas",
      places: "Lugares",
      countries: "Países",
      occupations: "Ocupaciones",
      occupationCountry: "Ocupación / País",
      eras: "Épocas",
      deaths: "Fallecimientos",
      about: "Acerca de",
      data: "Datos",
      permissions: "Permisos",
      download: "Descargar",
      api: "API",
      games: "Juegos",
      yearbook: "Anuario",
      birthle: "Birthle",
      trivia: "Trivia",
      news: "Noticias",
      search: "Buscar",
      home: "Inicio",
      giveFeedback: "Dar opinión",
      usageCitation: "Cita de uso",
      newBadge: "¡nuevo!",
    },
    readMoreWikipedia: "Leer más en Wikipedia",
    home: {
      tagline: "¡Explora la memoria colectiva humana!",
      subtitle:
        "Pantheon te ayuda a descubrir la geografía y la dinámica de la historia de nuestro planeta.",
      explore: "Explorar",
      people: "Personas",
      places: "Lugares",
      occupations: "Ocupaciones",
      and: "y",
      eras: "Épocas",
      trendingProfiles: "Perfiles en Tendencia Hoy",
      topProfilesBy: "Perfiles principales por vistas de página para la",
      wikipediaEdition: "edición de wikipedia",
      about:
        "es un observatorio de memoria colectiva enfocado en biografías con presencia en al menos",
      languages: "idiomas",
      aboutContinued:
        "en Wikipedia. Tenemos datos de más de 85,000 biografías, organizadas por países, ciudades, ocupaciones y épocas. Explora estos datos para conocer los personajes que dan forma a la cultura humana.",
      aboutDeveloped:
        "comenzó como un proyecto en el grupo de Aprendizaje Colectivo del MIT. Hoy es desarrollado por",
      datawheel: "Datawheel",
      aboutDatawheel:
        ", una empresa especializada en la creación de soluciones de distribución y visualización de datos.",
      recentPassings: "Fallecimientos Recientes",
      notableDeaths: "Muertes Notables de 2025",
      notableDeathsText:
        "¿Quieres ver la lista completa de figuras notables que hemos perdido en 2025? Visita nuestra",
      notableDeathsLink: "Muertes Notables de 2025",
      notableDeathsContinued:
        "página para una colección completa de biografías con personalidades influyentes, incluyendo celebridades, artistas, líderes e íconos culturales que han fallecido este año.",
      trendingSingers: "Cantantes en Tendencia Hoy",
      trendingActors: "Actores en Tendencia Hoy",
      searchPlaceholder: "Buscar personas, lugares y ocupaciones",
    },
    news: {
      pageTitle: "¿Quién es tendencia hoy?",
      pageSubtitle: "Resúmenes diarios de figuras históricas (generado por IA)",
      trendingIn: "Tendencia en",
      selectDate: "Seleccione una fecha diferente",
      references: "Referencias:",
      noData: "No hay datos de tendencias disponibles para esta fecha.",
      unknown: "Desconocido",
    },
    trending: {
      isTrendingToday: "¡{name} es tendencia hoy!",
      whyTrending: "¿Por qué {name} es tendencia?",
      references: "Fuentes:",
      viewMoreTrending: "Ver más personas en tendencia",
    },
  },
  fr: {
    stillAlive: "aujourd'hui",
    learnMoreRankless: "En savoir plus sur l'impact académique de {name} sur Rankless",
    intro: {
      rankingSentence: ({
        name,
        gender,
        l,
        l_prev,
        occupationRank,
        occupationRankPrev,
        occupation,
        occupationSlug,
        bplaceCountryRank,
        bplaceCountryRankPrev,
        country,
        countrySlug,
        bplaceCountryOccupationRank,
        demonym,
        formatOrdinal,
      }) => {
        let sentence = `Sa biographie est disponible en ${l} langues différentes sur Wikipédia`;
        if (l_prev && l !== l_prev) {
          sentence += ` (${l > l_prev ? "en hausse" : "en baisse"} de ${l_prev} en 2024)`;
        }
        sentence += ". ";

        const article = gender === "F" ? "la" : "le";
        sentence += `${name} est ${article} ${occupationRank === 1 ? "" : formatOrdinal(occupationRank)} <a href="/profile/occupation/${occupationSlug}">${occupation.toLowerCase()}</a> ${article === "la" ? "la plus populaire" : "le plus populaire"}`;
        if (occupationRankPrev && occupationRankPrev !== occupationRank) {
          sentence += ` (${occupationRank < occupationRankPrev ? "en hausse" : "en baisse"} du ${formatOrdinal(occupationRankPrev)} en 2024)`;
        }

        if (country) {
          sentence += `, ${article} ${bplaceCountryRank !== 1 ? formatOrdinal(bplaceCountryRank) : ""} biographie la plus populaire ${country.startsWith("É") || country.startsWith("I") ? "d'" : "de "}${country ? `<a href="/profile/place/${countrySlug}">${country}</a>` : ""}`;
          if (bplaceCountryRankPrev && bplaceCountryRankPrev !== bplaceCountryRank) {
            sentence += ` (${bplaceCountryRank < bplaceCountryRankPrev ? "en hausse" : "en baisse"} du ${formatOrdinal(bplaceCountryRankPrev)} en 2019)`;
          }

          if (bplaceCountryOccupationRank) {
            sentence += ` et ${article} ${bplaceCountryOccupationRank !== 1 ? formatOrdinal(bplaceCountryOccupationRank) : ""} <a href="/profile/occupation/${occupationSlug}/country/${countrySlug}">${occupation} ${demonym.toLowerCase()}</a> ${article === "la" ? "la plus populaire" : "le plus populaire"}`;
          }
        }

        sentence += ".";
        return sentence;
      },
    },
    nav: {
      visualizations: "Visualisations",
      rankings: "Classements",
      profiles: "Profils",
      people: "Personnes",
      places: "Lieux",
      countries: "Pays",
      occupations: "Professions",
      occupationCountry: "Profession / Pays",
      eras: "Époques",
      deaths: "Décès",
      about: "À propos",
      data: "Données",
      permissions: "Autorisations",
      download: "Télécharger",
      api: "API",
      games: "Jeux",
      yearbook: "Annuaire",
      birthle: "Birthle",
      trivia: "Trivia",
      news: "Actualités",
      search: "Rechercher",
      home: "Accueil",
      giveFeedback: "Donner votre avis",
      usageCitation: "Citation d'usage",
      newBadge: "nouveau !",
    },
    readMoreWikipedia: "En savoir plus sur Wikipédia",
    home: {
      tagline: "Explorez la mémoire collective humaine !",
      subtitle:
        "Pantheon vous aide à découvrir la géographie et la dynamique de l'histoire de notre planète.",
      explore: "Explorer",
      people: "Personnes",
      places: "Lieux",
      occupations: "Professions",
      and: "et",
      eras: "Époques",
      trendingProfiles: "Profils Tendance Aujourd'hui",
      topProfilesBy: "Meilleurs profils par vues de page pour l'",
      wikipediaEdition: "édition de wikipédia",
      about:
        "est un observatoire de la mémoire collective axé sur les biographies présentes dans au moins",
      languages: "langues",
      aboutContinued:
        "sur Wikipédia. Nous disposons de données sur plus de 85 000 biographies, organisées par pays, villes, professions et époques. Explorez ces données pour en savoir plus sur les personnages qui façonnent la culture humaine.",
      aboutDeveloped:
        "a commencé comme un projet du groupe Collective Learning au MIT. Aujourd'hui, il est développé par",
      datawheel: "Datawheel",
      aboutDatawheel:
        ", une entreprise spécialisée dans la création de solutions de distribution et de visualisation de données.",
      recentPassings: "Décès Récents",
      notableDeaths: "Décès Notables de 2025",
      notableDeathsText:
        "Vous voulez voir la liste complète des personnalités notables que nous avons perdues en 2025 ? Visitez notre",
      notableDeathsLink: "Décès Notables de 2025",
      notableDeathsContinued:
        "page pour une collection complète de biographies présentant des personnalités influentes, y compris des célébrités, des artistes, des dirigeants et des icônes culturelles décédés cette année.",
      trendingSingers: "Chanteurs Tendance Aujourd'hui",
      trendingActors: "Acteurs Tendance Aujourd'hui",
      searchPlaceholder: "Rechercher des personnes, des lieux et des professions",
    },
    news: {
      pageTitle: "Qui est en tendance aujourd'hui?",
      pageSubtitle:
        "Résumés quotidiens de personnages historiques (généré par IA)",
      trendingIn: "Tendance en",
      selectDate: "Sélectionner une date différente",
      references: "Références:",
      noData: "Aucune donnée de tendance disponible pour cette date.",
      unknown: "Inconnu",
    },
    trending: {
      isTrendingToday: "{name} est en tendance aujourd'hui !",
      whyTrending: "Pourquoi {name} est en tendance ?",
      references: "Sources :",
      viewMoreTrending: "Voir plus de personnes en tendance",
    },
  },
  de: {
    stillAlive: "heute",
    learnMoreRankless: "Erfahren Sie mehr über {name}s akademischen Einfluss bei Rankless",
    intro: {
      rankingSentence: ({
        name,
        gender,
        l,
        l_prev,
        occupationRank,
        occupationRankPrev,
        occupation,
        occupationSlug,
        bplaceCountryRank,
        bplaceCountryRankPrev,
        country,
        countrySlug,
        bplaceCountryOccupationRank,
        demonym,
        formatOrdinal,
      }) => {
        const possessive = gender === "M" ? "Seine" : gender === "F" ? "Ihre" : "Die";

        let sentence = `${possessive} Biografie ist in ${l} verschiedenen Sprachen auf Wikipedia verfügbar`;
        if (l_prev && l !== l_prev) {
          sentence += ` (${l > l_prev ? "gestiegen" : "gesunken"} von ${l_prev} im Jahr 2024)`;
        }
        sentence += ". ";

        const article = gender === "F" ? "die" : "der";
        sentence += `${name} ist ${article} ${occupationRank === 1 ? "" : formatOrdinal(occupationRank)} beliebteste <a href="/profile/occupation/${occupationSlug}">${occupation}</a>`;
        if (occupationRankPrev && occupationRankPrev !== occupationRank) {
          sentence += ` (${occupationRank < occupationRankPrev ? "gestiegen" : "gesunken"} vom ${formatOrdinal(occupationRankPrev)} im Jahr 2024)`;
        }

        if (country) {
          sentence += `, die ${bplaceCountryRank !== 1 ? formatOrdinal(bplaceCountryRank) : ""} beliebteste Biografie aus <a href="/profile/place/${countrySlug}">${country}</a>`;
          if (bplaceCountryRankPrev && bplaceCountryRankPrev !== bplaceCountryRank) {
            sentence += ` (${bplaceCountryRank < bplaceCountryRankPrev ? "gestiegen" : "gesunken"} vom ${formatOrdinal(bplaceCountryRankPrev)} im Jahr 2019)`;
          }

          if (bplaceCountryOccupationRank) {
            sentence += ` und ${article} ${bplaceCountryOccupationRank !== 1 ? formatOrdinal(bplaceCountryOccupationRank) : ""} beliebteste <a href="/profile/occupation/${occupationSlug}/country/${countrySlug}">${demonym} ${occupation}</a>`;
          }
        }

        sentence += ".";
        return sentence;
      },
    },
    nav: {
      visualizations: "Visualisierungen",
      rankings: "Ranglisten",
      profiles: "Profile",
      people: "Personen",
      places: "Orte",
      countries: "Länder",
      occupations: "Berufe",
      occupationCountry: "Beruf / Land",
      eras: "Epochen",
      deaths: "Todesfälle",
      about: "Über uns",
      data: "Daten",
      permissions: "Berechtigungen",
      download: "Herunterladen",
      api: "API",
      games: "Spiele",
      yearbook: "Jahrbuch",
      birthle: "Birthle",
      trivia: "Trivia",
      news: "Nachrichten",
      search: "Suchen",
      home: "Startseite",
      giveFeedback: "Feedback geben",
      usageCitation: "Zitatangabe",
      newBadge: "neu!",
    },
    readMoreWikipedia: "Mehr auf Wikipedia lesen",
    home: {
      tagline: "Erkunden Sie das kollektive Gedächtnis der Menschheit!",
      subtitle:
        "Pantheon hilft Ihnen, die Geografie und Dynamik der Geschichte unseres Planeten zu entdecken.",
      explore: "Erkunden",
      people: "Personen",
      places: "Orte",
      occupations: "Berufe",
      and: "und",
      eras: "Epochen",
      trendingProfiles: "Heute im Trend",
      topProfilesBy: "Top-Profile nach Seitenaufrufen für die",
      wikipediaEdition: "Wikipedia-Ausgabe",
      about:
        "ist ein Observatorium des kollektiven Gedächtnisses, das sich auf Biografien mit Präsenz in mindestens",
      languages: "Sprachen",
      aboutContinued:
        "in Wikipedia konzentriert. Wir haben Daten von mehr als 85.000 Biografien, organisiert nach Ländern, Städten, Berufen und Epochen. Erkunden Sie diese Daten, um mehr über die Persönlichkeiten zu erfahren, die die menschliche Kultur prägen.",
      aboutDeveloped:
        "begann als Projekt der Collective Learning-Gruppe am MIT. Heute wird es entwickelt von",
      datawheel: "Datawheel",
      aboutDatawheel:
        ", einem Unternehmen, das sich auf die Erstellung von Datenvertriebs- und Visualisierungslösungen spezialisiert hat.",
      recentPassings: "Kürzliche Todesfälle",
      notableDeaths: "Bedeutende Todesfälle von 2025",
      notableDeathsText:
        "Möchten Sie die vollständige Liste der bemerkenswerten Persönlichkeiten sehen, die wir 2025 verloren haben? Besuchen Sie unsere",
      notableDeathsLink: "Bedeutende Todesfälle von 2025",
      notableDeathsContinued:
        "Seite für eine umfassende Sammlung von Biografien einflussreicher Persönlichkeiten, darunter Prominente, Künstler, Führungspersönlichkeiten und kulturelle Ikonen, die dieses Jahr verstorben sind.",
      trendingSingers: "Sänger im Trend Heute",
      trendingActors: "Schauspieler im Trend Heute",
      searchPlaceholder: "Personen, Orte und Berufe suchen",
    },
    news: {
      pageTitle: "Wer ist heute im Trend?",
      pageSubtitle:
        "Tägliche Zusammenfassungen historischer Persönlichkeiten (von KI generiert)",
      trendingIn: "Im Trend in",
      selectDate: "Wählen Sie ein anderes Datum",
      references: "Referenzen:",
      noData: "Keine Trenddaten für dieses Datum verfügbar.",
      unknown: "Unbekannt",
    },
    trending: {
      isTrendingToday: "{name} ist heute im Trend!",
      whyTrending: "Warum {name} im Trend ist:",
      references: "Quellen:",
      viewMoreTrending: "Weitere Trendpersonen ansehen",
    },
  },
  ru: {
    stillAlive: "настоящее время",
    learnMoreRankless: "Узнайте больше о академическом влиянии {name} на Rankless",
    intro: {
      rankingSentence: ({
        name,
        gender,
        l,
        l_prev,
        occupationRank,
        occupationRankPrev,
        occupation,
        occupationSlug,
        bplaceCountryRank,
        bplaceCountryRankPrev,
        country,
        countrySlug,
        bplaceCountryOccupationRank,
        demonym,
        formatOrdinal,
      }) => {
        const possessive = gender === "M" ? "Его" : gender === "F" ? "Её" : "Их";

        let sentence = `${possessive} биография доступна на ${l} различных языках в Википедии`;
        if (l_prev && l !== l_prev) {
          sentence += ` (${l > l_prev ? "рост" : "снижение"} с ${l_prev} в 2024 году)`;
        }
        sentence += ". ";

        sentence += `${name} — ${occupationRank === 1 ? "" : formatOrdinal(occupationRank)} самый популярный <a href="/profile/occupation/${occupationSlug}">${occupation.toLowerCase()}</a>`;
        if (occupationRankPrev && occupationRankPrev !== occupationRank) {
          sentence += ` (${occupationRank < occupationRankPrev ? "рост" : "снижение"} с ${formatOrdinal(occupationRankPrev)} в 2024 году)`;
        }

        if (country) {
          sentence += `, ${bplaceCountryRank !== 1 ? formatOrdinal(bplaceCountryRank) : ""} самая популярная биография из <a href="/profile/place/${countrySlug}">${country}</a>`;
          if (bplaceCountryRankPrev && bplaceCountryRankPrev !== bplaceCountryRank) {
            sentence += ` (${bplaceCountryRank < bplaceCountryRankPrev ? "рост" : "снижение"} с ${formatOrdinal(bplaceCountryRankPrev)} в 2019 году)`;
          }

          if (bplaceCountryOccupationRank) {
            sentence += ` и ${bplaceCountryOccupationRank !== 1 ? formatOrdinal(bplaceCountryOccupationRank) : ""} самый популярный <a href="/profile/occupation/${occupationSlug}/country/${countrySlug}">${demonym} ${occupation.toLowerCase()}</a>`;
          }
        }

        sentence += ".";
        return sentence;
      },
    },
    nav: {
      visualizations: "Визуализации",
      rankings: "Рейтинги",
      profiles: "Профили",
      people: "Люди",
      places: "Места",
      countries: "Страны",
      occupations: "Профессии",
      occupationCountry: "Профессия / Страна",
      eras: "Эпохи",
      deaths: "Смерти",
      about: "О проекте",
      data: "Данные",
      permissions: "Разрешения",
      download: "Скачать",
      api: "API",
      games: "Игры",
      yearbook: "Ежегодник",
      birthle: "Birthle",
      trivia: "Викторина",
      news: "Новости",
      search: "Поиск",
      home: "Главная",
      giveFeedback: "Оставить отзыв",
      usageCitation: "Цитирование",
      newBadge: "новое!",
    },
    readMoreWikipedia: "Подробнее в Википедии",
    home: {
      tagline: "Исследуйте коллективную память человечества!",
      subtitle:
        "Pantheon помогает вам открыть географию и динамику истории нашей планеты.",
      explore: "Исследовать",
      people: "Люди",
      places: "Места",
      occupations: "Профессии",
      and: "и",
      eras: "Эпохи",
      trendingProfiles: "Популярные Профили Сегодня",
      topProfilesBy: "Лучшие профили по просмотрам страниц для",
      wikipediaEdition: "издания Википедии",
      about:
        "это обсерватория коллективной памяти, сосредоточенная на биографиях, присутствующих как минимум в",
      languages: "языках",
      aboutContinued:
        "в Википедии. У нас есть данные о более чем 85 000 биографий, организованных по странам, городам, профессиям и эпохам. Исследуйте эти данные, чтобы узнать о персонажах, которые формируют человеческую культуру.",
      aboutDeveloped:
        "начался как проект группы Collective Learning в MIT. Сегодня он разрабатывается",
      datawheel: "Datawheel",
      aboutDatawheel:
        ", компанией, специализирующейся на создании решений для распространения и визуализации данных.",
      recentPassings: "Недавние Уходы",
      notableDeaths: "Известные Смерти 2025 Года",
      notableDeathsText:
        "Хотите увидеть полный список известных личностей, которых мы потеряли в 2025 году? Посетите нашу",
      notableDeathsLink: "Известные Смерти 2025 Года",
      notableDeathsContinued:
        "страницу для полной коллекции биографий влиятельных личностей, включая знаменитостей, артистов, лидеров и культурных икон, которые скончались в этом году.",
      trendingSingers: "Популярные Певцы Сегодня",
      trendingActors: "Популярные Актеры Сегодня",
      searchPlaceholder: "Поиск людей, мест и профессий",
    },
    news: {
      pageTitle: "Кто в тренде сегодня?",
      pageSubtitle:
        "Ежедневные сводки о исторических личностях (сгенерировано ИИ)",
      trendingIn: "В тренде в",
      selectDate: "Выберите другую дату",
      references: "Ссылки:",
      noData: "Нет данных о трендах для этой даты.",
      unknown: "Неизвестно",
    },
    trending: {
      isTrendingToday: "{name} сегодня в тренде!",
      whyTrending: "Почему {name} в тренде:",
      references: "Источники:",
      viewMoreTrending: "Показать больше людей в тренде",
    },
  },
  zh: {
    stillAlive: "至今",
    learnMoreRankless: "在Rankless上了解更多关于{name}的学术影响",
    intro: {
      rankingSentence: ({
        name,
        gender,
        l,
        l_prev,
        occupationRank,
        occupationRankPrev,
        occupation,
        occupationSlug,
        bplaceCountryRank,
        bplaceCountryRankPrev,
        country,
        countrySlug,
        bplaceCountryOccupationRank,
        demonym,
        formatOrdinal,
      }) => {
        const possessive = gender === "M" ? "他" : gender === "F" ? "她" : "他们";

        let sentence = `${possessive}的传记有${l}种不同语言的维基百科版本`;
        if (l_prev && l !== l_prev) {
          sentence += `（${l > l_prev ? "增加" : "减少"}自2024年的${l_prev}种）`;
        }
        sentence += "。";

        sentence += `${name}是第${occupationRank === 1 ? "" : formatOrdinal(occupationRank)}最受欢迎的<a href="/profile/occupation/${occupationSlug}">${occupation}</a>`;
        if (occupationRankPrev && occupationRankPrev !== occupationRank) {
          sentence += `（${occupationRank < occupationRankPrev ? "上升" : "下降"}自2024年的第${formatOrdinal(occupationRankPrev)}）`;
        }

        if (country) {
          sentence += `，第${bplaceCountryRank !== 1 ? formatOrdinal(bplaceCountryRank) : ""}最受欢迎的<a href="/profile/place/${countrySlug}">${country}</a>传记`;
          if (bplaceCountryRankPrev && bplaceCountryRankPrev !== bplaceCountryRank) {
            sentence += `（${bplaceCountryRank < bplaceCountryRankPrev ? "上升" : "下降"}自2019年的第${formatOrdinal(bplaceCountryRankPrev)}）`;
          }

          if (bplaceCountryOccupationRank) {
            sentence += `，以及第${bplaceCountryOccupationRank !== 1 ? formatOrdinal(bplaceCountryOccupationRank) : ""}最受欢迎的<a href="/profile/occupation/${occupationSlug}/country/${countrySlug}">${demonym}${occupation}</a>`;
          }
        }

        sentence += "。";
        return sentence;
      },
    },
    nav: {
      visualizations: "可视化",
      rankings: "排名",
      profiles: "档案",
      people: "人物",
      places: "地点",
      countries: "国家",
      occupations: "职业",
      occupationCountry: "职业 / 国家",
      eras: "时代",
      deaths: "逝世",
      about: "关于",
      data: "数据",
      permissions: "权限",
      download: "下载",
      api: "API",
      games: "游戏",
      yearbook: "年鉴",
      birthle: "Birthle",
      trivia: "问答",
      news: "新闻",
      search: "搜索",
      home: "首页",
      giveFeedback: "提供反馈",
      usageCitation: "引用说明",
      newBadge: "新！",
    },
    readMoreWikipedia: "在维基百科上阅读更多",
    home: {
      tagline: "探索人类集体记忆！",
      subtitle: "Pantheon帮助您发现我们星球历史的地理和动态。",
      explore: "探索",
      people: "人物",
      places: "地点",
      occupations: "职业",
      and: "和",
      eras: "时代",
      trendingProfiles: "今日热门人物",
      topProfilesBy: "按页面浏览量排名的热门人物",
      wikipediaEdition: "维基百科版本",
      about: "是一个专注于集体记忆的观测站，关注至少在",
      languages: "种语言",
      aboutContinued:
        "的维基百科中出现的传记。我们拥有超过85,000个传记的数据，按国家、城市、职业和时代组织。探索这些数据，了解塑造人类文化的人物。",
      aboutDeveloped: "最初是麻省理工学院集体学习小组的一个项目。今天它由",
      datawheel: "Datawheel",
      aboutDatawheel: "开发，这是一家专门从事数据分发和可视化解决方案的公司。",
      recentPassings: "最近去世",
      notableDeaths: "2025年著名人物逝世",
      notableDeathsText:
        "想查看我们在2025年失去的著名人物的完整名单吗？访问我们的",
      notableDeathsLink: "2025年著名人物逝世",
      notableDeathsContinued:
        "页面，查看包括名人、艺术家、领导者和文化偶像在内的今年去世的有影响力人物的全面传记集。",
      trendingSingers: "今日热门歌手",
      trendingActors: "今日热门演员",
      searchPlaceholder: "搜索人物、地点和职业",
    },
    news: {
      pageTitle: "今日热门人物",
      pageSubtitle: "历史人物每日摘要（由AI生成）",
      trendingIn: "热门于",
      selectDate: "选择其他日期",
      references: "参考资料：",
      noData: "此日期无趋势数据。",
      unknown: "未知",
    },
    trending: {
      isTrendingToday: "{name} 今天正在流行！",
      whyTrending: "{name} 为何走红：",
      references: "来源: ",
      viewMoreTrending: "查看更多热门人物",
    },
  },
  ja: {
    stillAlive: "現在",
    learnMoreRankless: "Ranklessで{name}の学術的影響について詳しく知る",
    intro: {
      rankingSentence: ({
        name,
        gender,
        l,
        l_prev,
        occupationRank,
        occupationRankPrev,
        occupation,
        occupationSlug,
        bplaceCountryRank,
        bplaceCountryRankPrev,
        country,
        countrySlug,
        bplaceCountryOccupationRank,
        demonym,
        formatOrdinal,
      }) => {
        const possessive = gender === "M" ? "彼" : gender === "F" ? "彼女" : "その人物";

        let sentence = `${possessive}の伝記は${l}の異なる言語のウィキペディアで利用可能です`;
        if (l_prev && l !== l_prev) {
          sentence += `（2024年の${l_prev}から${l > l_prev ? "増加" : "減少"}）`;
        }
        sentence += "。";

        sentence += `${name}は${occupationRank === 1 ? "" : "第" + formatOrdinal(occupationRank)}最も人気のある<a href="/profile/occupation/${occupationSlug}">${occupation}</a>です`;
        if (occupationRankPrev && occupationRankPrev !== occupationRank) {
          sentence += `（2024年の第${formatOrdinal(occupationRankPrev)}から${occupationRank < occupationRankPrev ? "上昇" : "下降"}）`;
        }

        if (country) {
          sentence += `、<a href="/profile/place/${countrySlug}">${country}</a>出身で${bplaceCountryRank !== 1 ? "第" + formatOrdinal(bplaceCountryRank) : ""}最も人気のある伝記`;
          if (bplaceCountryRankPrev && bplaceCountryRankPrev !== bplaceCountryRank) {
            sentence += `（2019年の第${formatOrdinal(bplaceCountryRankPrev)}から${bplaceCountryRank < bplaceCountryRankPrev ? "上昇" : "下降"}）`;
          }

          if (bplaceCountryOccupationRank) {
            sentence += `、そして${bplaceCountryOccupationRank !== 1 ? "第" + formatOrdinal(bplaceCountryOccupationRank) : ""}最も人気のある<a href="/profile/occupation/${occupationSlug}/country/${countrySlug}">${demonym}の${occupation}</a>です`;
          }
        }

        sentence += "。";
        return sentence;
      },
    },
    nav: {
      visualizations: "可視化",
      rankings: "ランキング",
      profiles: "プロフィール",
      people: "人物",
      places: "場所",
      countries: "国",
      occupations: "職業",
      occupationCountry: "職業 / 国",
      eras: "時代",
      deaths: "死去",
      about: "概要",
      data: "データ",
      permissions: "許可",
      download: "ダウンロード",
      api: "API",
      games: "ゲーム",
      yearbook: "年鑑",
      birthle: "Birthle",
      trivia: "トリビア",
      news: "ニュース",
      search: "検索",
      home: "ホーム",
      giveFeedback: "フィードバック",
      usageCitation: "引用方法",
      newBadge: "新着！",
    },
    readMoreWikipedia: "ウィキペディアで詳細を読む",
    home: {
      tagline: "人類の集合的記憶を探求しよう！",
      subtitle:
        "Pantheonは、私たちの惑星の歴史の地理と動態を発見するのに役立ちます。",
      explore: "探索",
      people: "人物",
      places: "場所",
      occupations: "職業",
      and: "と",
      eras: "時代",
      trendingProfiles: "本日のトレンド人物",
      topProfilesBy: "ページビューによるトッププロフィール",
      wikipediaEdition: "ウィキペディア版",
      about: "は、少なくとも",
      languages: "言語",
      aboutContinued:
        "のウィキペディアに存在する伝記に焦点を当てた集合的記憶の観測所です。私たちは、国、都市、職業、時代別に整理された85,000以上の伝記のデータを持っています。このデータを探索して、人間文化を形作る人物について学びましょう。",
      aboutDeveloped:
        "は、MITのCollective Learningグループのプロジェクトとして始まりました。今日、それは",
      datawheel: "Datawheel",
      aboutDatawheel:
        "によって開発されています。これは、データ配信と可視化ソリューションの作成を専門とする会社です。",
      recentPassings: "最近の訃報",
      notableDeaths: "2025年の著名人の死",
      notableDeathsText:
        "2025年に失った著名人の完全なリストを見たいですか？私たちの",
      notableDeathsLink: "2025年の著名人の死",
      notableDeathsContinued:
        "ページにアクセスして、今年亡くなった有名人、芸術家、指導者、文化的アイコンなど、影響力のある人物の伝記の包括的なコレクションをご覧ください。",
      trendingSingers: "本日のトレンド歌手",
      trendingActors: "本日のトレンド俳優",
      searchPlaceholder: "人物、場所、職業を検索",
    },
    news: {
      pageTitle: "今日のトレンド人物",
      pageSubtitle: "歴史上の人物の毎日のサマリー（AI生成）",
      trendingIn: "トレンド：",
      selectDate: "別の日付を選択",
      references: "参考文献：",
      noData: "この日付の トレンドデータはありません。",
      unknown: "不明",
    },
    trending: {
      isTrendingToday: "{name} が今日のトレンドです！",
      whyTrending: "{name} がトレンドの理由",
      references: "出典：",
      viewMoreTrending: "他のトレンド人物を見る",
    },
  },
  ar: {
    stillAlive: "حتى اليوم",
    learnMoreRankless: "تعرف على المزيد حول التأثير الأكاديمي لـ {name} في Rankless",
    intro: {
      rankingSentence: ({
        name,
        gender,
        l,
        l_prev,
        occupationRank,
        occupationRankPrev,
        occupation,
        occupationSlug,
        bplaceCountryRank,
        bplaceCountryRankPrev,
        country,
        countrySlug,
        bplaceCountryOccupationRank,
        demonym,
        formatOrdinal,
      }) => {
        const biographyWord = gender === "F" ? "سيرتها الذاتية" : "سيرته الذاتية";

        let sentence = `${biographyWord} متاحة بـ ${l} لغة مختلفة في ويكيبيديا`;
        if (l_prev && l !== l_prev) {
          sentence += ` (${l > l_prev ? "زيادة" : "انخفاض"} من ${l_prev} في 2024)`;
        }
        sentence += ". ";

        const isPopular = gender === "F" ? "الأكثر شعبية" : "الأكثر شعبية";
        sentence += `${name} هو ${occupationRank === 1 ? "" : formatOrdinal(occupationRank)} <a href="/profile/occupation/${occupationSlug}">${occupation}</a> ${isPopular}`;
        if (occupationRankPrev && occupationRankPrev !== occupationRank) {
          sentence += ` (${occupationRank < occupationRankPrev ? "ارتفع" : "انخفض"} من ${formatOrdinal(occupationRankPrev)} في 2024)`;
        }

        if (country) {
          sentence += `، ${bplaceCountryRank !== 1 ? formatOrdinal(bplaceCountryRank) : ""} السيرة الذاتية الأكثر شعبية من <a href="/profile/place/${countrySlug}">${country}</a>`;
          if (bplaceCountryRankPrev && bplaceCountryRankPrev !== bplaceCountryRank) {
            sentence += ` (${bplaceCountryRank < bplaceCountryRankPrev ? "ارتفع" : "انخفض"} من ${formatOrdinal(bplaceCountryRankPrev)} في 2019)`;
          }

          if (bplaceCountryOccupationRank) {
            sentence += ` و${bplaceCountryOccupationRank !== 1 ? formatOrdinal(bplaceCountryOccupationRank) : ""} <a href="/profile/occupation/${occupationSlug}/country/${countrySlug}">${occupation} ${demonym}</a> ${isPopular}`;
          }
        }

        sentence += ".";
        return sentence;
      },
    },
    nav: {
      visualizations: "التصورات",
      rankings: "التصنيفات",
      profiles: "الملفات الشخصية",
      people: "الأشخاص",
      places: "الأماكن",
      countries: "البلدان",
      occupations: "المهن",
      occupationCountry: "المهنة / البلد",
      eras: "العصور",
      deaths: "الوفيات",
      about: "حول",
      data: "البيانات",
      permissions: "الأذونات",
      download: "تحميل",
      api: "API",
      games: "الألعاب",
      yearbook: "الكتاب السنوي",
      birthle: "Birthle",
      trivia: "أسئلة ثقافية",
      news: "الأخبار",
      search: "بحث",
      home: "الرئيسية",
      giveFeedback: "إرسال ملاحظات",
      usageCitation: "الاستشهاد",
      newBadge: "جديد!",
    },
    readMoreWikipedia: "اقرأ المزيد على ويكيبيديا",
    home: {
      tagline: "استكشف الذاكرة الجماعية للبشرية!",
      subtitle: "يساعدك Pantheon على اكتشاف جغرافية وديناميكية تاريخ كوكبنا.",
      explore: "استكشف",
      people: "أشخاص",
      places: "أماكن",
      occupations: "مهن",
      and: "و",
      eras: "عصور",
      trendingProfiles: "الملفات الشخصية الرائجة اليوم",
      topProfilesBy: "أفضل الملفات الشخصية حسب مشاهدات الصفحة لـ",
      wikipediaEdition: "إصدار ويكيبيديا",
      about: "هو مرصد للذاكرة الجماعية يركز على السير الذاتية الموجودة في",
      languages: "لغة على الأقل",
      aboutContinued:
        "في ويكيبيديا. لدينا بيانات عن أكثر من 85,000 سيرة ذاتية، منظمة حسب البلدان والمدن والمهن والعصور. استكشف هذه البيانات للتعرف على الشخصيات التي تشكل الثقافة الإنسانية.",
      aboutDeveloped:
        "بدأ كمشروع في مجموعة التعلم الجماعي في معهد ماساتشوستس للتكنولوجيا. اليوم تم تطويره بواسطة",
      datawheel: "Datawheel",
      aboutDatawheel: "، وهي شركة متخصصة في إنشاء حلول توزيع وتصور البيانات.",
      recentPassings: "الوفيات الأخيرة",
      notableDeaths: "الوفيات البارزة لعام 2025",
      notableDeathsText:
        "هل تريد رؤية القائمة الكاملة للشخصيات البارزة التي فقدناها في عام 2025؟ قم بزيارة",
      notableDeathsLink: "الوفيات البارزة لعام 2025",
      notableDeathsContinued:
        "صفحتنا للحصول على مجموعة شاملة من السير الذاتية للشخصيات المؤثرة، بما في ذلك المشاهير والفنانين والقادة والأيقونات الثقافية الذين توفوا هذا العام.",
      trendingSingers: "المطربون الرائجون اليوم",
      trendingActors: "الممثلون الرائجون اليوم",
      searchPlaceholder: "البحث عن الأشخاص والأماكن والمهن",
    },
    news: {
      pageTitle: "من هو في الموضة اليوم؟",
      pageSubtitle:
        "ملخصات يومية للشخصيات التاريخية (تم إنشاؤها بواسطة الذكاء الاصطناعي)",
      trendingIn: "رائج في",
      selectDate: "اختر تاريخًا مختلفًا",
      references: "المراجع:",
      noData: "لا تتوفر بيانات الاتجاهات لهذا التاريخ.",
      unknown: "غير معروف",
    },
    trending: {
      isTrendingToday: "{name} رائج اليوم!",
      whyTrending: "لماذا {name} رائج:",
      references: "المصادر:",
      viewMoreTrending: "عرض المزيد من الأشخاص الرائجين",
    },
  },
  it: {
    stillAlive: "presente",
    learnMoreRankless: "Scopri di più sull'impatto accademico di {name} su Rankless",
    intro: {
      rankingSentence: ({
        name,
        gender,
        l,
        l_prev,
        occupationRank,
        occupationRankPrev,
        occupation,
        occupationSlug,
        bplaceCountryRank,
        bplaceCountryRankPrev,
        country,
        countrySlug,
        bplaceCountryOccupationRank,
        demonym,
        formatOrdinal,
      }) => {
        let sentence = `La sua biografia è disponibile in ${l} lingue diverse su Wikipedia`;
        if (l_prev && l !== l_prev) {
          sentence += ` (${l > l_prev ? "in aumento" : "in calo"} da ${l_prev} nel 2024)`;
        }
        sentence += ". ";

        const article = gender === "F" ? "la" : "il";
        const popular = gender === "F" ? "più popolare" : "più popolare";
        sentence += `${name} è ${article} ${occupationRank === 1 ? "" : formatOrdinal(occupationRank)} <a href="/profile/occupation/${occupationSlug}">${occupation.toLowerCase()}</a> ${popular}`;
        if (occupationRankPrev && occupationRankPrev !== occupationRank) {
          sentence += ` (${occupationRank < occupationRankPrev ? "in aumento" : "in calo"} dal ${formatOrdinal(occupationRankPrev)} nel 2024)`;
        }

        if (country) {
          sentence += `, la ${bplaceCountryRank !== 1 ? formatOrdinal(bplaceCountryRank) : ""} biografia più popolare ${country.startsWith("I") || country.startsWith("E") ? "d'" : "di "}${country ? `<a href="/profile/place/${countrySlug}">${country}</a>` : ""}`;
          if (bplaceCountryRankPrev && bplaceCountryRankPrev !== bplaceCountryRank) {
            sentence += ` (${bplaceCountryRank < bplaceCountryRankPrev ? "in aumento" : "in calo"} dal ${formatOrdinal(bplaceCountryRankPrev)} nel 2019)`;
          }

          if (bplaceCountryOccupationRank) {
            sentence += ` e ${article} ${bplaceCountryOccupationRank !== 1 ? formatOrdinal(bplaceCountryOccupationRank) : ""} <a href="/profile/occupation/${occupationSlug}/country/${countrySlug}">${occupation} ${demonym.toLowerCase()}</a> ${popular}`;
          }
        }

        sentence += ".";
        return sentence;
      },
    },
    nav: {
      visualizations: "Visualizzazioni",
      rankings: "Classifiche",
      profiles: "Profili",
      people: "Persone",
      places: "Luoghi",
      countries: "Paesi",
      occupations: "Professioni",
      occupationCountry: "Professione / Paese",
      eras: "Ere",
      deaths: "Decessi",
      about: "Informazioni",
      data: "Dati",
      permissions: "Permessi",
      download: "Scarica",
      api: "API",
      games: "Giochi",
      yearbook: "Annuario",
      birthle: "Birthle",
      trivia: "Trivia",
      news: "Notizie",
      search: "Cerca",
      home: "Home",
      giveFeedback: "Lascia un feedback",
      usageCitation: "Citazione d'uso",
      newBadge: "nuovo!",
    },
    readMoreWikipedia: "Leggi di più su Wikipedia",
    home: {
      tagline: "Esplora la memoria collettiva umana!",
      subtitle:
        "Pantheon ti aiuta a scoprire la geografia e le dinamiche della storia del nostro pianeta.",
      explore: "Esplora",
      people: "Persone",
      places: "Luoghi",
      occupations: "Professioni",
      and: "e",
      eras: "Ere",
      trendingProfiles: "Profili di Tendenza Oggi",
      topProfilesBy: "Profili principali per visualizzazioni di pagina per l'",
      wikipediaEdition: "edizione di wikipedia",
      about:
        "è un osservatorio della memoria collettiva focalizzato su biografie con presenza in almeno",
      languages: "lingue",
      aboutContinued:
        "su Wikipedia. Abbiamo dati su oltre 85.000 biografie, organizzate per paesi, città, professioni ed ere. Esplora questi dati per conoscere i personaggi che plasmano la cultura umana.",
      aboutDeveloped:
        "è iniziato come progetto del gruppo Collective Learning al MIT. Oggi è sviluppato da",
      datawheel: "Datawheel",
      aboutDatawheel:
        ", un'azienda specializzata nella creazione di soluzioni di distribuzione e visualizzazione dati.",
      recentPassings: "Scomparse Recenti",
      notableDeaths: "Morti Notevoli del 2025",
      notableDeathsText:
        "Vuoi vedere l'elenco completo delle figure notevoli che abbiamo perso nel 2025? Visita la nostra",
      notableDeathsLink: "Morti Notevoli del 2025",
      notableDeathsContinued:
        "pagina per una raccolta completa di biografie di personalità influenti, tra cui celebrità, artisti, leader e icone culturali scomparse quest'anno.",
      trendingSingers: "Cantanti di Tendenza Oggi",
      trendingActors: "Attori di Tendenza Oggi",
      searchPlaceholder: "Cerca persone, luoghi e professioni",
    },
    news: {
      pageTitle: "Chi è di tendenza oggi?",
      pageSubtitle:
        "Riassunti quotidiani di personaggi storici (generato da IA)",
      trendingIn: "Di tendenza in",
      selectDate: "Seleziona una data diversa",
      references: "Riferimenti:",
      noData: "Nessun dato di tendenza disponibile per questa data.",
      unknown: "Sconosciuto",
    },
    trending: {
      isTrendingToday: "{name} è di tendenza oggi!",
      whyTrending: "Perché {name} è di tendenza:",
      references: "Fonti:",
      viewMoreTrending: "Vedi altre persone di tendenza",
    },
  },
  pt: {
    stillAlive: "presente",
    learnMoreRankless: "Saiba mais sobre o impacto acadêmico de {name} no Rankless",
    intro: {
      rankingSentence: ({
        name,
        gender,
        l,
        l_prev,
        occupationRank,
        occupationRankPrev,
        occupation,
        occupationSlug,
        bplaceCountryRank,
        bplaceCountryRankPrev,
        country,
        countrySlug,
        bplaceCountryOccupationRank,
        demonym,
        formatOrdinal,
      }) => {
        let sentence = `Sua biografia está disponível em ${l} idiomas diferentes na Wikipédia`;
        if (l_prev && l !== l_prev) {
          sentence += ` (${l > l_prev ? "aumento" : "redução"} de ${l_prev} em 2024)`;
        }
        sentence += ". ";

        const article = gender === "F" ? "a" : "o";
        const popular = gender === "F" ? "mais popular" : "mais popular";
        sentence += `${name} é ${article} ${occupationRank === 1 ? "" : formatOrdinal(occupationRank)} <a href="/profile/occupation/${occupationSlug}">${occupation.toLowerCase()}</a> ${popular}`;
        if (occupationRankPrev && occupationRankPrev !== occupationRank) {
          sentence += ` (${occupationRank < occupationRankPrev ? "subiu" : "caiu"} do ${formatOrdinal(occupationRankPrev)} em 2024)`;
        }

        if (country) {
          sentence += `, a ${bplaceCountryRank !== 1 ? formatOrdinal(bplaceCountryRank) : ""} biografia mais popular ${country.startsWith("A") || country.startsWith("E") || country.startsWith("I") || country.startsWith("O") || country.startsWith("U") ? "d" : "de "}${country ? `<a href="/profile/place/${countrySlug}">${country}</a>` : ""}`;
          if (bplaceCountryRankPrev && bplaceCountryRankPrev !== bplaceCountryRank) {
            sentence += ` (${bplaceCountryRank < bplaceCountryRankPrev ? "subiu" : "caiu"} do ${formatOrdinal(bplaceCountryRankPrev)} em 2019)`;
          }

          if (bplaceCountryOccupationRank) {
            sentence += ` e ${article} ${bplaceCountryOccupationRank !== 1 ? formatOrdinal(bplaceCountryOccupationRank) : ""} <a href="/profile/occupation/${occupationSlug}/country/${countrySlug}">${occupation} ${demonym.toLowerCase()}</a> ${popular}`;
          }
        }

        sentence += ".";
        return sentence;
      },
    },
    nav: {
      visualizations: "Visualizações",
      rankings: "Classificações",
      profiles: "Perfis",
      people: "Pessoas",
      places: "Lugares",
      countries: "Países",
      occupations: "Profissões",
      occupationCountry: "Profissão / País",
      eras: "Eras",
      deaths: "Falecimentos",
      about: "Sobre",
      data: "Dados",
      permissions: "Permissões",
      download: "Baixar",
      api: "API",
      games: "Jogos",
      yearbook: "Anuário",
      birthle: "Birthle",
      trivia: "Trivia",
      news: "Notícias",
      search: "Pesquisar",
      home: "Início",
      giveFeedback: "Enviar feedback",
      usageCitation: "Citação de uso",
      newBadge: "novo!",
    },
    readMoreWikipedia: "Leia mais na Wikipédia",
    home: {
      tagline: "Explore a memória coletiva humana!",
      subtitle:
        "Pantheon ajuda você a descobrir a geografia e a dinâmica da história do nosso planeta.",
      explore: "Explorar",
      people: "Pessoas",
      places: "Lugares",
      occupations: "Ocupações",
      and: "e",
      eras: "Eras",
      trendingProfiles: "Perfis em Alta Hoje",
      topProfilesBy: "Principais perfis por visualizações de página para a",
      wikipediaEdition: "edição da wikipédia",
      about:
        "é um observatório da memória coletiva focado em biografias com presença em pelo menos",
      languages: "idiomas",
      aboutContinued:
        "na Wikipédia. Temos dados sobre mais de 85.000 biografias, organizadas por países, cidades, ocupações e eras. Explore esses dados para conhecer os personagens que moldam a cultura humana.",
      aboutDeveloped:
        "começou como um projeto no grupo Collective Learning do MIT. Hoje é desenvolvido pela",
      datawheel: "Datawheel",
      aboutDatawheel:
        ", uma empresa especializada na criação de soluções de distribuição e visualização de dados.",
      recentPassings: "Falecimentos Recentes",
      notableDeaths: "Mortes Notáveis de 2025",
      notableDeathsText:
        "Quer ver a lista completa de figuras notáveis que perdemos em 2025? Visite nossa",
      notableDeathsLink: "Mortes Notáveis de 2025",
      notableDeathsContinued:
        "página para uma coleção abrangente de biografias de personalidades influentes, incluindo celebridades, artistas, líderes e ícones culturais que faleceram este ano.",
      trendingSingers: "Cantores em Alta Hoje",
      trendingActors: "Atores em Alta Hoje",
      searchPlaceholder: "Pesquisar pessoas, lugares e profissões",
    },
    news: {
      pageTitle: "Quem está em alta hoje?",
      pageSubtitle: "Resumos diários de figuras históricas (gerado por IA)",
      trendingIn: "Em alta em",
      selectDate: "Selecione uma data diferente",
      references: "Referências:",
      noData: "Nenhum dado de tendência disponível para esta data.",
      unknown: "Desconhecido",
    },
    trending: {
      isTrendingToday: "{name} está em alta hoje!",
      whyTrending: "Por que {name} está em alta?",
      references: "Referências:",
      viewMoreTrending: "Ver mais pessoas em alta",
    },
  },
  hu: {
    stillAlive: "napjainkig",
    learnMoreRankless: "Tudjon meg többet {name} akadémiai hatásáról a Rankless-en",
    intro: {
      rankingSentence: ({
        name,
        gender,
        l,
        l_prev,
        occupationRank,
        occupationRankPrev,
        occupation,
        occupationSlug,
        bplaceCountryRank,
        bplaceCountryRankPrev,
        country,
        countrySlug,
        bplaceCountryOccupationRank,
        demonym,
        formatOrdinal,
      }) => {
        let sentence = `Életrajza ${l} különböző nyelven érhető el a Wikipédián`;
        if (l_prev && l !== l_prev) {
          sentence += ` (${l > l_prev ? "növekedés" : "csökkenés"} ${l_prev}-ről 2024-ben)`;
        }
        sentence += ". ";

        sentence += `${name} a ${occupationRank === 1 ? "" : formatOrdinal(occupationRank)} legnépszerűbb <a href="/profile/occupation/${occupationSlug}">${occupation.toLowerCase()}</a>`;
        if (occupationRankPrev && occupationRankPrev !== occupationRank) {
          sentence += ` (${occupationRank < occupationRankPrev ? "növekedés" : "csökkenés"} a ${formatOrdinal(occupationRankPrev)}-ről 2024-ben)`;
        }

        if (country) {
          sentence += `, a ${bplaceCountryRank !== 1 ? formatOrdinal(bplaceCountryRank) : ""} legnépszerűbb életrajz <a href="/profile/place/${countrySlug}">${country}</a> országából`;
          if (bplaceCountryRankPrev && bplaceCountryRankPrev !== bplaceCountryRank) {
            sentence += ` (${bplaceCountryRank < bplaceCountryRankPrev ? "növekedés" : "csökkenés"} a ${formatOrdinal(bplaceCountryRankPrev)}-ről 2019-ben)`;
          }

          if (bplaceCountryOccupationRank) {
            sentence += ` és a ${bplaceCountryOccupationRank !== 1 ? formatOrdinal(bplaceCountryOccupationRank) : ""} legnépszerűbb <a href="/profile/occupation/${occupationSlug}/country/${countrySlug}">${demonym} ${occupation.toLowerCase()}</a>`;
          }
        }

        sentence += ".";
        return sentence;
      },
    },
    nav: {
      visualizations: "Vizualizációk",
      rankings: "Rangsorok",
      profiles: "Profilok",
      people: "Személyek",
      places: "Helyek",
      countries: "Országok",
      occupations: "Foglalkozások",
      occupationCountry: "Foglalkozás / Ország",
      eras: "Korszakok",
      deaths: "Halálozások",
      about: "Rólunk",
      data: "Adatok",
      permissions: "Engedélyek",
      download: "Letöltés",
      api: "API",
      games: "Játékok",
      yearbook: "Évkönyv",
      birthle: "Birthle",
      trivia: "Kvíz",
      news: "Hírek",
      search: "Keresés",
      home: "Kezdőlap",
      giveFeedback: "Visszajelzés küldése",
      usageCitation: "Hivatkozás",
      newBadge: "új!",
    },
    readMoreWikipedia: "Bővebben a Wikipédián",
    home: {
      tagline: "Fedezze fel az emberiség kollektív emlékezetét!",
      subtitle:
        "A Pantheon segít felfedezni bolygónk történetének földrajzát és dinamikáját.",
      explore: "Felfedezés",
      people: "Emberek",
      places: "Helyek",
      occupations: "Foglalkozások",
      and: "és",
      eras: "Korszakok",
      trendingProfiles: "Ma Felkapott Profilok",
      topProfilesBy: "Legjobb profilok oldalmegtekintések alapján a",
      wikipediaEdition: "wikipédia kiadáshoz",
      about: "a kollektív memória megfigyelője, amely legalább",
      languages: "nyelven",
      aboutContinued:
        "jelenlévő életrajzokra összpontosít a Wikipédián. Több mint 85 000 életrajz adataival rendelkezünk, országok, városok, foglalkozások és korszakok szerint rendszerezve. Fedezze fel ezeket az adatokat, hogy megismerje az emberi kultúrát formáló személyiségeket.",
      aboutDeveloped:
        "az MIT Collective Learning csoportjának projektjeként indult. Ma a",
      datawheel: "Datawheel",
      aboutDatawheel:
        " fejleszti, egy adatterjesztési és vizualizációs megoldások létrehozására szakosodott vállalat.",
      recentPassings: "Közelmúltbeli Elhunytak",
      notableDeaths: "2025 Kiemelkedő Halálozásai",
      notableDeathsText:
        "Szeretné látni a 2025-ben elvesztett kiemelkedő személyiségek teljes listáját? Látogassa meg a",
      notableDeathsLink: "2025 Kiemelkedő Halálozásai",
      notableDeathsContinued:
        "oldalunkat a befolyásos személyiségek átfogó életrajzi gyűjteményéért, beleértve a hírességeket, művészeket, vezetőket és kulturális ikonokat, akik idén hunytak el.",
      trendingSingers: "Ma Felkapott Énekesek",
      trendingActors: "Ma Felkapott Színészek",
      searchPlaceholder: "Személyek, helyek és foglalkozások keresése",
    },
    news: {
      pageTitle: "Ki a felkapott ma?",
      pageSubtitle:
        "Történelmi személyiségek napi összefoglalói (AI által generálva)",
      trendingIn: "Felkapott:",
      selectDate: "Válasszon más dátumot",
      references: "Hivatkozások:",
      noData: "Nincs elérhető trendinformáció ehhez a dátumhoz.",
      unknown: "Ismeretlen",
    },
    trending: {
      isTrendingToday: "{name} ma felkapott!",
      whyTrending: "Miért felkapott {name}:",
      references: "Hivatkozások:",
      viewMoreTrending: "További felkapott személyek",
    },
  },
  nl: {
    stillAlive: "heden",
    learnMoreRankless: "Meer informatie over de academische impact van {name} op Rankless",
    intro: {
      rankingSentence: ({
        name,
        gender,
        l,
        l_prev,
        occupationRank,
        occupationRankPrev,
        occupation,
        occupationSlug,
        bplaceCountryRank,
        bplaceCountryRankPrev,
        country,
        countrySlug,
        bplaceCountryOccupationRank,
        demonym,
        formatOrdinal,
      }) => {
        const possessive = gender === "M" ? "Zijn" : gender === "F" ? "Haar" : "Hun";

        let sentence = `${possessive} biografie is beschikbaar in ${l} verschillende talen op Wikipedia`;
        if (l_prev && l !== l_prev) {
          sentence += ` (${l > l_prev ? "toegenomen" : "afgenomen"} van ${l_prev} in 2024)`;
        }
        sentence += ". ";

        sentence += `${name} is de ${occupationRank === 1 ? "" : formatOrdinal(occupationRank)} populairste <a href="/profile/occupation/${occupationSlug}">${occupation.toLowerCase()}</a>`;
        if (occupationRankPrev && occupationRankPrev !== occupationRank) {
          sentence += ` (${occupationRank < occupationRankPrev ? "gestegen" : "gedaald"} van ${formatOrdinal(occupationRankPrev)} in 2024)`;
        }

        if (country) {
          sentence += `, de ${bplaceCountryRank !== 1 ? formatOrdinal(bplaceCountryRank) : ""} populairste biografie uit <a href="/profile/place/${countrySlug}">${country}</a>`;
          if (bplaceCountryRankPrev && bplaceCountryRankPrev !== bplaceCountryRank) {
            sentence += ` (${bplaceCountryRank < bplaceCountryRankPrev ? "gestegen" : "gedaald"} van ${formatOrdinal(bplaceCountryRankPrev)} in 2019)`;
          }

          if (bplaceCountryOccupationRank) {
            sentence += ` en de ${bplaceCountryOccupationRank !== 1 ? formatOrdinal(bplaceCountryOccupationRank) : ""} populairste <a href="/profile/occupation/${occupationSlug}/country/${countrySlug}">${demonym} ${occupation.toLowerCase()}</a>`;
          }
        }

        sentence += ".";
        return sentence;
      },
    },
    nav: {
      visualizations: "Visualisaties",
      rankings: "Rankings",
      profiles: "Profielen",
      people: "Personen",
      places: "Plaatsen",
      countries: "Landen",
      occupations: "Beroepen",
      occupationCountry: "Beroep / Land",
      eras: "Tijdperken",
      deaths: "Overledenen",
      about: "Over",
      data: "Gegevens",
      permissions: "Toestemmingen",
      download: "Downloaden",
      api: "API",
      games: "Spellen",
      yearbook: "Jaarboek",
      birthle: "Birthle",
      trivia: "Trivia",
      news: "Nieuws",
      search: "Zoeken",
      home: "Home",
      giveFeedback: "Feedback geven",
      usageCitation: "Citatie voor gebruik",
      newBadge: "nieuw!",
    },
    readMoreWikipedia: "Lees meer op Wikipedia",
    home: {
      tagline: "Verken het collectieve geheugen van de mensheid!",
      subtitle:
        "Pantheon helpt je de geografie en dynamiek van de geschiedenis van onze planeet te ontdekken.",
      explore: "Verkennen",
      people: "Mensen",
      places: "Plaatsen",
      occupations: "Beroepen",
      and: "en",
      eras: "Tijdperken",
      trendingProfiles: "Trending Profielen Vandaag",
      topProfilesBy: "Topprofielen op basis van paginaweergaven voor de",
      wikipediaEdition: "wikipedia-editie",
      about:
        "is een observatorium van collectief geheugen gericht op biografieën met aanwezigheid in minstens",
      languages: "talen",
      aboutContinued:
        "op Wikipedia. We hebben gegevens over meer dan 85.000 biografieën, georganiseerd per land, stad, beroep en tijdperk. Verken deze gegevens om meer te leren over de karakters die de menselijke cultuur vormgeven.",
      aboutDeveloped:
        "begon als een project bij de Collective Learning-groep aan MIT. Vandaag wordt het ontwikkeld door",
      datawheel: "Datawheel",
      aboutDatawheel:
        ", een bedrijf gespecialiseerd in het creëren van datadistributie- en visualisatieoplossingen.",
      recentPassings: "Recente Overlijdens",
      notableDeaths: "Opmerkelijke Sterfgevallen van 2025",
      notableDeathsText:
        "Wil je de volledige lijst zien van opmerkelijke figuren die we in 2025 verloren hebben? Bezoek onze",
      notableDeathsLink: "Opmerkelijke Sterfgevallen van 2025",
      notableDeathsContinued:
        "pagina voor een uitgebreide verzameling biografieën van invloedrijke persoonlijkheden, waaronder beroemdheden, artiesten, leiders en culturele iconen die dit jaar zijn overleden.",
      trendingSingers: "Trending Zangers Vandaag",
      trendingActors: "Trending Acteurs Vandaag",
      searchPlaceholder: "Zoek personen, plaatsen en beroepen",
    },
    news: {
      pageTitle: "Wie is vandaag trending?",
      pageSubtitle:
        "Dagelijkse samenvattingen van historische figuren (gegenereerd door AI)",
      trendingIn: "Trending in",
      selectDate: "Selecteer een andere datum",
      references: "Referenties:",
      noData: "Geen trendgegevens beschikbaar voor deze datum.",
      unknown: "Onbekend",
    },
    trending: {
      isTrendingToday: "{name} is vandaag trending!",
      whyTrending: "Waarom {name} trending is:",
      references: "Referenties:",
      viewMoreTrending: "Meer trending mensen bekijken",
    },
  },
  pl: {
    stillAlive: "obecnie",
    learnMoreRankless: "Dowiedz się więcej o akademickim wpływie {name} na Rankless",
    intro: {
      rankingSentence: ({
        name,
        gender,
        l,
        l_prev,
        occupationRank,
        occupationRankPrev,
        occupation,
        occupationSlug,
        bplaceCountryRank,
        bplaceCountryRankPrev,
        country,
        countrySlug,
        bplaceCountryOccupationRank,
        demonym,
        formatOrdinal,
      }) => {
        const possessive = gender === "M" ? "Jego" : gender === "F" ? "Jej" : "Ich";

        let sentence = `${possessive} biografia jest dostępna w ${l} różnych językach w Wikipedii`;
        if (l_prev && l !== l_prev) {
          sentence += ` (${l > l_prev ? "wzrost" : "spadek"} z ${l_prev} w 2024 roku)`;
        }
        sentence += ". ";

        sentence += `${name} jest ${occupationRank === 1 ? "" : formatOrdinal(occupationRank)} najpopularniejszym <a href="/profile/occupation/${occupationSlug}">${occupation.toLowerCase()}</a>`;
        if (occupationRankPrev && occupationRankPrev !== occupationRank) {
          sentence += ` (${occupationRank < occupationRankPrev ? "wzrost" : "spadek"} z ${formatOrdinal(occupationRankPrev)} w 2024 roku)`;
        }

        if (country) {
          sentence += `, ${bplaceCountryRank !== 1 ? formatOrdinal(bplaceCountryRank) : ""} najpopularniejszą biografią z <a href="/profile/place/${countrySlug}">${country}</a>`;
          if (bplaceCountryRankPrev && bplaceCountryRankPrev !== bplaceCountryRank) {
            sentence += ` (${bplaceCountryRank < bplaceCountryRankPrev ? "wzrost" : "spadek"} z ${formatOrdinal(bplaceCountryRankPrev)} w 2019 roku)`;
          }

          if (bplaceCountryOccupationRank) {
            sentence += ` oraz ${bplaceCountryOccupationRank !== 1 ? formatOrdinal(bplaceCountryOccupationRank) : ""} najpopularniejszym <a href="/profile/occupation/${occupationSlug}/country/${countrySlug}">${demonym.toLowerCase()} ${occupation.toLowerCase()}</a>`;
          }
        }

        sentence += ".";
        return sentence;
      },
    },
    nav: {
      visualizations: "Wizualizacje",
      rankings: "Rankingi",
      profiles: "Profile",
      people: "Osoby",
      places: "Miejsca",
      countries: "Kraje",
      occupations: "Zawody",
      occupationCountry: "Zawód / Kraj",
      eras: "Epoki",
      deaths: "Zgony",
      about: "O nas",
      data: "Dane",
      permissions: "Uprawnienia",
      download: "Pobierz",
      api: "API",
      games: "Gry",
      yearbook: "Rocznik",
      birthle: "Birthle",
      trivia: "Trivia",
      news: "Aktualności",
      search: "Szukaj",
      home: "Strona główna",
      giveFeedback: "Prześlij opinię",
      usageCitation: "Cytowanie",
      newBadge: "nowość!",
    },
    readMoreWikipedia: "Czytaj więcej w Wikipedii",
    home: {
      tagline: "Odkryj zbiorową pamięć ludzkości!",
      subtitle:
        "Pantheon pomaga odkryć geografię i dynamikę historii naszej planety.",
      explore: "Odkrywaj",
      people: "Ludzie",
      places: "Miejsca",
      occupations: "Zawody",
      and: "i",
      eras: "Epoki",
      trendingProfiles: "Profile w Trendach Dzisiaj",
      topProfilesBy: "Najlepsze profile według wyświetleń strony dla",
      wikipediaEdition: "edycji wikipedii",
      about:
        "to obserwatorium pamięci zbiorowej skupione na biografiach obecnych w co najmniej",
      languages: "językach",
      aboutContinued:
        "w Wikipedii. Mamy dane dotyczące ponad 85 000 biografii, zorganizowanych według krajów, miast, zawodów i epok. Odkrywaj te dane, aby poznać postacie kształtujące kulturę ludzką.",
      aboutDeveloped:
        "rozpoczął się jako projekt grupy Collective Learning na MIT. Dziś jest rozwijany przez",
      datawheel: "Datawheel",
      aboutDatawheel:
        ", firmę specjalizującą się w tworzeniu rozwiązań dystrybucji i wizualizacji danych.",
      recentPassings: "Niedawne Zgony",
      notableDeaths: "Znaczące Zgony 2025",
      notableDeathsText:
        "Chcesz zobaczyć pełną listę znaczących postaci, które straciliśmy w 2025 roku? Odwiedź naszą",
      notableDeathsLink: "Znaczące Zgony 2025",
      notableDeathsContinued:
        "stronę, aby uzyskać obszerną kolekcję biografii wpływowych osobistości, w tym celebrytów, artystów, liderów i ikon kulturowych, którzy zmarli w tym roku.",
      trendingSingers: "Piosenkarze w Trendach Dzisiaj",
      trendingActors: "Aktorzy w Trendach Dzisiaj",
      searchPlaceholder: "Szukaj osób, miejsc i zawodów",
    },
    news: {
      pageTitle: "Kto jest dziś w trendach?",
      pageSubtitle:
        "Codzienne podsumowania postaci historycznych (wygenerowane przez AI)",
      trendingIn: "W trendach w",
      selectDate: "Wybierz inną datę",
      references: "Odniesienia:",
      noData: "Brak danych o trendach dla tej daty.",
      unknown: "Nieznany",
    },
    trending: {
      isTrendingToday: "{name} jest dziś w trendach!",
      whyTrending: "Dlaczego {name} jest w trendach:",
      references: "Źródła:",
      viewMoreTrending: "Zobacz więcej osób w trendach",
    },
  },
};

// Helper function to get translations for a specific locale
export function getTranslations(locale, defaultLocale = "en") {
  return translations[locale] || translations[defaultLocale];
}
