// UI translations for different languages
export const translations = {
  en: {
    news: {
      pageTitle: "Who is Trending Today?",
      pageSubtitle: "Daily summaries of historical figures (generated by AI)",
      trendingIn: "Trending in",
      selectDate: "Select a different date",
      references: "References:",
      noData: "No trending data available for this date.",
      unknown: "Unknown",
    },
  },
  es: {
    news: {
      pageTitle: "¿Quién es tendencia hoy?",
      pageSubtitle: "Resúmenes diarios de figuras históricas (generado por IA)",
      trendingIn: "Tendencia en",
      selectDate: "Seleccione una fecha diferente",
      references: "Referencias:",
      noData: "No hay datos de tendencias disponibles para esta fecha.",
      unknown: "Desconocido",
    },
  },
  fr: {
    news: {
      pageTitle: "Qui est en tendance aujourd'hui?",
      pageSubtitle: "Résumés quotidiens de personnages historiques (généré par IA)",
      trendingIn: "Tendance en",
      selectDate: "Sélectionner une date différente",
      references: "Références:",
      noData: "Aucune donnée de tendance disponible pour cette date.",
      unknown: "Inconnu",
    },
  },
  de: {
    news: {
      pageTitle: "Wer ist heute im Trend?",
      pageSubtitle: "Tägliche Zusammenfassungen historischer Persönlichkeiten (von KI generiert)",
      trendingIn: "Im Trend in",
      selectDate: "Wählen Sie ein anderes Datum",
      references: "Referenzen:",
      noData: "Keine Trenddaten für dieses Datum verfügbar.",
      unknown: "Unbekannt",
    },
  },
  ru: {
    news: {
      pageTitle: "Кто в тренде сегодня?",
      pageSubtitle: "Ежедневные сводки о исторических личностях (сгенерировано ИИ)",
      trendingIn: "В тренде в",
      selectDate: "Выберите другую дату",
      references: "Ссылки:",
      noData: "Нет данных о трендах для этой даты.",
      unknown: "Неизвестно",
    },
  },
  zh: {
    news: {
      pageTitle: "今日热门人物",
      pageSubtitle: "历史人物每日摘要（由AI生成）",
      trendingIn: "热门于",
      selectDate: "选择其他日期",
      references: "参考资料：",
      noData: "此日期无趋势数据。",
      unknown: "未知",
    },
  },
  ja: {
    news: {
      pageTitle: "今日のトレンド人物",
      pageSubtitle: "歴史上の人物の毎日のサマリー（AI生成）",
      trendingIn: "トレンド：",
      selectDate: "別の日付を選択",
      references: "参考文献：",
      noData: "この日付の トレンドデータはありません。",
      unknown: "不明",
    },
  },
  ar: {
    news: {
      pageTitle: "من هو في الموضة اليوم؟",
      pageSubtitle: "ملخصات يومية للشخصيات التاريخية (تم إنشاؤها بواسطة الذكاء الاصطناعي)",
      trendingIn: "رائج في",
      selectDate: "اختر تاريخًا مختلفًا",
      references: "المراجع:",
      noData: "لا تتوفر بيانات الاتجاهات لهذا التاريخ.",
      unknown: "غير معروف",
    },
  },
  it: {
    news: {
      pageTitle: "Chi è di tendenza oggi?",
      pageSubtitle: "Riassunti quotidiani di personaggi storici (generato da IA)",
      trendingIn: "Di tendenza in",
      selectDate: "Seleziona una data diversa",
      references: "Riferimenti:",
      noData: "Nessun dato di tendenza disponibile per questa data.",
      unknown: "Sconosciuto",
    },
  },
  pt: {
    news: {
      pageTitle: "Quem está em alta hoje?",
      pageSubtitle: "Resumos diários de figuras históricas (gerado por IA)",
      trendingIn: "Em alta em",
      selectDate: "Selecione uma data diferente",
      references: "Referências:",
      noData: "Nenhum dado de tendência disponível para esta data.",
      unknown: "Desconhecido",
    },
  },
  hu: {
    news: {
      pageTitle: "Ki a felkapott ma?",
      pageSubtitle: "Történelmi személyiségek napi összefoglalói (AI által generálva)",
      trendingIn: "Felkapott:",
      selectDate: "Válasszon más dátumot",
      references: "Hivatkozások:",
      noData: "Nincs elérhető trendinformáció ehhez a dátumhoz.",
      unknown: "Ismeretlen",
    },
  },
  nl: {
    news: {
      pageTitle: "Wie is vandaag trending?",
      pageSubtitle: "Dagelijkse samenvattingen van historische figuren (gegenereerd door AI)",
      trendingIn: "Trending in",
      selectDate: "Selecteer een andere datum",
      references: "Referenties:",
      noData: "Geen trendgegevens beschikbaar voor deze datum.",
      unknown: "Onbekend",
    },
  },
  pl: {
    news: {
      pageTitle: "Kto jest dziś w trendach?",
      pageSubtitle: "Codzienne podsumowania postaci historycznych (wygenerowane przez AI)",
      trendingIn: "W trendach w",
      selectDate: "Wybierz inną datę",
      references: "Odniesienia:",
      noData: "Brak danych o trendach dla tej daty.",
      unknown: "Nieznany",
    },
  },
};

// Helper function to get translations for a specific locale
export function getTranslations(locale, defaultLocale = "en") {
  return translations[locale] || translations[defaultLocale];
}
